from __future__ import annotations

from typing import Any

TRIAL_CRITERIA_REGISTRY: dict[str, dict[str, Any]] = {'AFFIRM': {'biomarker_required': None,
            'citation': 'Scher HI et al. AFFIRM. NEJM 2012;367:1187-1197.',
            'endpoint_primary': 'OS',
            'evidence_level': 'level_1_category_1',
            'exclusion': ['Seizure history', 'Brain metastases', 'Severe cardiovascular disease'],
            'inclusion': ['mCRPC progressing on docetaxel', 'ECOG 0-2', 'Adequate organ function'],
            'nct': 'NCT00974311',
            'pmid': '22894553',
            'regimen_tested': 'Enzalutamide 160 mg vs placebo (post-docetaxel mCRPC)',
            'stage': 'm1_crpc'},
 'AFT-19': {'biomarker_required': None,
            'citation': 'Aggarwal R et al. PRESTO/AFT-19. JCO 2023;41:3169-3181.',
            'endpoint_primary': 'PSA-PFS',
            'evidence_level': 'level_2_category_2A',
            'exclusion': ['See PRESTO'],
            'inclusion': ['See PRESTO'],
            'nct': 'NCT03009981',
            'pmid': '37000748',
            'regimen_tested': 'Same as PRESTO',
            'stage': 'recurrence_bcr'},
 'ALSYMPCA': {'biomarker_required': None,
              'citation': 'Parker C et al. ALSYMPCA. NEJM 2013;369:213-223.',
              'endpoint_primary': 'OS',
              'evidence_level': 'level_1_category_1',
              'exclusion': ['Visceral metastases', 'Lymph nodes >3 cm', 'Imminent spinal cord compression'],
              'inclusion': ['mCRPC with symptomatic bone metastases',
                            '≥2 bone mets, no visceral mets',
                            'ECOG 0-2',
                            'Adequate hematologic reserve'],
              'nct': 'NCT00699751',
              'pmid': '23863050',
              'regimen_tested': 'Radium-223 dichloride 50 kBq/kg q4w x6 vs placebo',
              'stage': 'm1_crpc'},
 'AMPLITUDE': {'biomarker_required': 'HRR mutation',
               'citation': 'Rathkopf D et al. AMPLITUDE. NEJM 2024;391:2197-2209.',
               'endpoint_primary': 'rPFS',
               'evidence_level': 'level_1_category_1',
               'exclusion': ['Prior PARP inhibitor', 'MDS/AML', 'Visceral crisis'],
               'inclusion': ['mCSPC (newly diagnosed)', 'HRR mutation (BRCA1/BRCA2/CDK12/PALB2/ATM/etc.)', 'ECOG 0-1'],
               'nct': 'NCT04497844',
               'pmid': '39527709',
               'regimen_tested': 'Niraparib + abiraterone + prednisone vs placebo + abi (HRR+ mCSPC)',
               'stage': 'mcspc'},
 'ARAMIS': {'biomarker_required': None,
            'citation': 'Fizazi K et al. ARAMIS. NEJM 2019;380:1235-1246.',
            'endpoint_primary': 'MFS',
            'evidence_level': 'level_1_category_1',
            'exclusion': ['Distant metastases', 'Severe cardiovascular disease', 'Hepatic impairment Child-Pugh C'],
            'inclusion': ['Non-metastatic CRPC',
                          'PSA doubling time ≤10 months',
                          'PSA ≥2 ng/mL',
                          'Castrate testosterone',
                          'ECOG 0-1'],
            'nct': 'NCT02200614',
            'pmid': '30763142',
            'regimen_tested': 'ADT + darolutamide 600 mg BID vs ADT + placebo',
            'stage': 'm0_crpc'},
 'ARANOTE': {'biomarker_required': None,
             'citation': 'Saad F et al. ARANOTE. JCO 2024;42(suppl):3055.',
             'endpoint_primary': 'rPFS',
             'evidence_level': 'level_1_category_1',
             'exclusion': ['Prior systemic therapy', 'Brain metastases', 'Severe cardiovascular disease'],
             'inclusion': ['Metastatic hormone-sensitive prostate cancer',
                           'ECOG 0-1',
                           'Not candidates for or declining docetaxel'],
             'nct': 'NCT04736199',
             'pmid': '39312707',
             'regimen_tested': 'ADT + darolutamide vs ADT + placebo (without docetaxel)',
             'stage': 'mcspc'},
 'ARASENS': {'biomarker_required': None,
             'citation': 'Smith MR et al. ARASENS. NEJM 2022;386:1132-1142.',
             'endpoint_primary': 'OS',
             'evidence_level': 'level_1_category_1',
             'exclusion': ['Prior systemic therapy excluding ADT (max 12 weeks)',
                           'Brain metastases',
                           'Significant hepatic impairment'],
             'inclusion': ['Newly diagnosed metastatic hormone-sensitive prostate cancer',
                           'ECOG 0-1',
                           'Candidates for ADT + docetaxel'],
             'nct': 'NCT02799602',
             'pmid': '35179323',
             'regimen_tested': 'ADT + docetaxel + darolutamide (triplet) vs ADT + docetaxel',
             'stage': 'mcspc',
             'subgroups': ['high_volume', 'low_volume']},
 'ARCHES': {'biomarker_required': None,
            'citation': 'Armstrong AJ et al. ARCHES. JCO 2019;37:2974-2986.',
            'endpoint_primary': 'rPFS',
            'evidence_level': 'level_1_category_1',
            'exclusion': ['Prior systemic therapy excluding ADT/first-gen anti-androgen',
                          'Brain metastases',
                          'Clinically significant cardiovascular disease'],
            'inclusion': ['Metastatic hormone-sensitive prostate cancer',
                          'ECOG 0-1',
                          'Documented progression on ADT (failure required)'],
            'nct': 'NCT02677896',
            'pmid': '31329516',
            'regimen_tested': 'ADT + enzalutamide 160 mg vs ADT + placebo',
            'stage': 'mcspc',
            'subgroups': ['high_volume', 'low_volume']},
 'ARO-96-02': {'biomarker_required': None,
               'citation': 'Wiegel T et al. ARO 96-02. JCO 2009;27:2924-2930.',
               'endpoint_primary': 'BCR-free survival',
               'evidence_level': 'level_1_category_1',
               'exclusion': ['Persistent PSA', 'Distant mets'],
               'inclusion': ['Post-RP pT3 or margins+', 'PSA undetectable post-RP'],
               'nct': 'NCT00667069',
               'pmid': '19286551',
               'regimen_tested': 'Adjuvant RT vs observation post-RP (pT3 or margins+)',
               'stage': 'post_prostatectomy'},
 'ARTISTIC': {'biomarker_required': None,
              'citation': 'Vale CL et al. ARTISTIC meta-analysis. Lancet 2020;396:1422-1431.',
              'endpoint_primary': 'Event-free survival',
              'evidence_level': 'level_1_meta',
              'exclusion': ['Distant metastases'],
              'inclusion': ['Pooled analysis of RADICALS-RT, GETUG-17, RAVES', 'Post-RP adverse features'],
              'nct': 'Multiple',
              'pmid': '33002431',
              'regimen_tested': 'Adjuvant RT vs early salvage RT (meta-analysis)',
              'stage': 'post_prostatectomy'},
 'CARD': {'biomarker_required': None,
          'citation': 'de Wit R et al. CARD. NEJM 2019;381:2506-2518.',
          'endpoint_primary': 'rPFS',
          'evidence_level': 'level_1_category_1',
          'exclusion': ['Severe neuropathy', 'Active infection'],
          'inclusion': ['mCRPC with progression on docetaxel AND prior ARPI (abi/enza ≤12 months)',
                        'ECOG 0-2',
                        'Adequate organ function'],
          'nct': 'NCT02485691',
          'pmid': '31566937',
          'regimen_tested': 'Cabazitaxel vs ARPI switch (after docetaxel + prior ARPI)',
          'stage': 'm1_crpc'},
 'CHAARTED': {'biomarker_required': None,
              'citation': 'Sweeney CJ et al. CHAARTED. NEJM 2015;373:737-746.',
              'endpoint_primary': 'Overall survival (OS)',
              'evidence_level': 'level_1_category_1',
              'exclusion': ['Prior cytotoxic chemotherapy for prostate cancer',
                            'Major surgery within 30 days',
                            'Active second malignancy'],
              'inclusion': ['Metastatic prostate adenocarcinoma confirmed by histology',
                            'ECOG 0-2',
                            'Adequate hepatic/renal function',
                            'High-volume disease defined as: visceral mets OR ≥4 bone mets with ≥1 beyond vertebral '
                            'column/pelvis'],
              'nct': 'NCT00309985',
              'pmid': '26244877',
              'regimen_tested': 'ADT + docetaxel 75 mg/m² q3w x6',
              'stage': 'mcspc',
              'subgroups': ['high_volume', 'low_volume']},
 'CONTACT-02': {'biomarker_required': None,
                'citation': 'Agarwal N et al. CONTACT-02. JCO 2024;42(suppl):LBA18.',
                'endpoint_primary': 'rPFS + OS',
                'evidence_level': 'level_1_category_1',
                'exclusion': ['Brain mets', 'Active autoimmune disease', 'Prior immune checkpoint inhibitor'],
                'inclusion': ['mCRPC progressing on 1 prior ARPI', 'Measurable soft tissue disease', 'ECOG 0-1'],
                'nct': 'NCT04446117',
                'pmid': '39245045',
                'regimen_tested': 'Cabozantinib + atezolizumab vs ARPI switch (post-1 ARPI mCRPC)',
                'stage': 'm1_crpc'},
 'COU-AA-301': {'biomarker_required': None,
                'citation': 'de Bono JS et al. COU-AA-301. NEJM 2011;364:1995-2005.',
                'endpoint_primary': 'OS',
                'evidence_level': 'level_1_category_1',
                'exclusion': ['Severe hepatic impairment (Child-Pugh C)',
                              'Uncontrolled hypertension',
                              'Significant cardiovascular disease'],
                'inclusion': ['mCRPC progressing on docetaxel', 'ECOG 0-2', 'Adequate organ function'],
                'nct': 'NCT00638690',
                'pmid': '21612468',
                'regimen_tested': 'Abiraterone 1000 mg + prednisone 5 mg BID vs placebo (post-docetaxel)',
                'stage': 'm1_crpc'},
 'COU-AA-302': {'biomarker_required': None,
                'citation': 'Ryan CJ et al. COU-AA-302. NEJM 2013;368:138-148.',
                'endpoint_primary': 'rPFS + OS',
                'evidence_level': 'level_1_category_1',
                'exclusion': ['Visceral metastases at significant burden',
                              'Pain requiring opioids',
                              'Hepatic Child-Pugh C'],
                'inclusion': ['Asymptomatic or mildly symptomatic mCRPC',
                              'Chemo-naïve (no prior cytotoxic chemo)',
                              'ECOG 0-1'],
                'nct': 'NCT00887198',
                'pmid': '23228172',
                'regimen_tested': 'Abiraterone + prednisone vs placebo (chemo-naïve mCRPC)',
                'stage': 'm1_crpc'},
 'EMBARK': {'biomarker_required': None,
            'citation': 'Freedland SJ et al. EMBARK. NEJM 2023;389:1453-1465.',
            'endpoint_primary': 'MFS',
            'evidence_level': 'level_1_category_1',
            'exclusion': ['Distant metastases', 'Seizure history', 'Severe cardiovascular disease'],
            'inclusion': ['BCR after RP and/or RT (PSA ≥1 post-RP or ≥nadir+2 post-RT)',
                          'PSA doubling time ≤9 months',
                          'No metastases on conventional imaging',
                          'ECOG 0-1'],
            'nct': 'NCT02319837',
            'pmid': '37877679',
            'regimen_tested': 'Enzalutamide + LHRH agonist vs LHRH alone vs enza monotherapy',
            'stage': 'recurrence_bcr'},
 'ENZAMET': {'biomarker_required': None,
             'citation': 'Davis ID et al. ENZAMET. NEJM 2019;381:121-131.',
             'endpoint_primary': 'OS',
             'evidence_level': 'level_1_category_1',
             'exclusion': ['Prior chemo allowed if completed ≥12 weeks before',
                           'Seizure disorder or risk factors for seizure',
                           'Significant cardiovascular disease (recent MI, stroke)'],
             'inclusion': ['Metastatic hormone-sensitive prostate cancer (mHSPC)',
                           'ECOG 0-2',
                           'Started ADT within 12 weeks before randomization',
                           'Adequate organ function'],
             'nct': 'NCT02446405',
             'pmid': '31157970',
             'regimen_tested': 'ADT + enzalutamide 160 mg vs ADT + standard non-steroidal antiandrogen',
             'stage': 'mcspc',
             'subgroups': ['high_volume', 'low_volume', 'with_or_without_docetaxel']},
 'GETUG-AFU-16': {'biomarker_required': None,
                  'citation': 'Carrie C et al. GETUG-AFU 16. Lancet Oncol 2016;17:747-756.',
                  'endpoint_primary': 'Progression-free survival (5-year)',
                  'evidence_level': 'level_1_category_1',
                  'exclusion': ['Distant mets', 'Prior pelvic RT'],
                  'inclusion': ['BCR post-RP with PSA ≥0.2 to ≤2.0', 'ECOG 0-1'],
                  'nct': 'NCT00423475',
                  'pmid': '27160475',
                  'regimen_tested': 'Salvage RT + 6-month ADT (goserelin) vs salvage RT alone',
                  'stage': 'recurrence_bcr'},
 'IMPACT': {'biomarker_required': None,
            'citation': 'Kantoff PW et al. IMPACT. NEJM 2010;363:411-422.',
            'endpoint_primary': 'OS',
            'evidence_level': 'level_1_category_1',
            'exclusion': ['Visceral mets (excluded)', 'Pain requiring opioids', 'Significant immunosuppression'],
            'inclusion': ['Asymptomatic or mildly symptomatic mCRPC',
                          'ECOG 0-1',
                          'No visceral metastases',
                          'Castrate testosterone'],
            'nct': 'NCT00065442',
            'pmid': '20818862',
            'regimen_tested': 'Sipuleucel-T (autologous APC immunotherapy) vs placebo',
            'stage': 'm1_crpc'},
 'IPATential150': {'biomarker_required': 'PTEN biallelic loss (IHC + NGS)',
                   'citation': 'Sweeney C et al. IPATential150. Lancet 2021;398:131-142.',
                   'endpoint_primary': 'rPFS in PTEN-loss + ITT',
                   'evidence_level': 'level_1_category_1',
                   'exclusion': ['Diabetes type 1 or insulin-dependent type 2',
                                 'Brain metastases',
                                 'Prior ARPI for mCRPC'],
                   'inclusion': ['Newly diagnosed mCRPC (1st-line)',
                                 'PTEN-loss subgroup (ITT also analyzed)',
                                 'ECOG 0-1'],
                   'nct': 'NCT03072238',
                   'pmid': '34293272',
                   'regimen_tested': 'Ipatasertib (AKT inhibitor) + abiraterone vs abi + placebo (1L mCRPC)',
                   'stage': 'm1_crpc'},
 'LATITUDE': {'biomarker_required': None,
              'citation': 'Fizazi K et al. LATITUDE. NEJM 2017;377:352-360.',
              'endpoint_primary': 'OS + rPFS (co-primary)',
              'evidence_level': 'level_1_category_1',
              'exclusion': ['Prior systemic therapy for prostate cancer',
                            'Active or symptomatic visceral disease (within 14 days)',
                            'Severe hepatic impairment (Child-Pugh C)'],
              'inclusion': ['Newly diagnosed metastatic high-risk castration-sensitive prostate cancer',
                            '≥2 of 3 high-risk factors: Gleason ≥8, ≥3 bone lesions, visceral metastasis',
                            'ECOG 0-2'],
              'nct': 'NCT01715285',
              'pmid': '28578607',
              'regimen_tested': 'ADT + abiraterone 1000 mg + prednisone 5 mg',
              'stage': 'mcspc',
              'subgroups': ['high_risk_3_factors', 'high_risk_2_factors']},
 'MAGNITUDE': {'biomarker_required': 'HRR positive (BRCA1/2/ATM/CDK12/etc.)',
               'citation': 'Chi KN et al. MAGNITUDE. JCO 2022;40:2293-2306.',
               'endpoint_primary': 'rPFS',
               'evidence_level': 'level_1_category_1',
               'exclusion': ['Prior systemic therapy for mCRPC', 'MDS/AML', 'Brain metastases'],
               'inclusion': ['Newly diagnosed mCRPC (1st-line)',
                             'HRR mutation (positive cohort) or biomarker-negative cohort',
                             'ECOG 0-2'],
               'nct': 'NCT03748641',
               'pmid': '35867349',
               'regimen_tested': 'Niraparib + abiraterone + prednisone vs abi + placebo (1L mCRPC)',
               'stage': 'm1_crpc'},
 'PEACE-1': {'biomarker_required': None,
             'citation': 'Fizazi K et al. PEACE-1. Lancet 2022;399:1695-1707.',
             'endpoint_primary': 'rPFS + OS',
             'evidence_level': 'level_1_category_1',
             'exclusion': ['Prior systemic therapy for metastatic disease',
                           'Brain or leptomeningeal metastases',
                           'Severe cardiovascular disease'],
             'inclusion': ['De novo metastatic castration-sensitive prostate cancer',
                           'ECOG 0-2',
                           'Adequate hepatic, renal, hematologic function'],
             'nct': 'NCT01957436',
             'pmid': '35430030',
             'regimen_tested': 'ADT + docetaxel + abiraterone (triplet) vs ADT + docetaxel',
             'stage': 'mcspc',
             'subgroups': ['with_local_RT', 'high_volume', 'low_volume']},
 'PEACE-3': {'biomarker_required': None,
             'citation': 'Gillessen S et al. PEACE-3. ESMO 2024 LBA.',
             'endpoint_primary': 'rPFS',
             'evidence_level': 'level_1_category_1',
             'exclusion': ['Visceral mets', 'Lymph nodes >3 cm'],
             'inclusion': ['mCRPC with ≥2 bone mets', 'Asymptomatic/mildly symptomatic', 'ECOG 0-1'],
             'nct': 'NCT02194842',
             'pmid': '37000748',
             'regimen_tested': 'Enzalutamide + radium-223 vs enza alone (bone mets mCRPC)',
             'stage': 'm1_crpc'},
 'PIVOT': {'biomarker_required': None,
           'citation': 'Wilt TJ et al. PIVOT. NEJM 2017;377:132-142 (long-term).',
           'endpoint_primary': 'OS',
           'evidence_level': 'level_1_category_1',
           'exclusion': ['Metastatic disease', 'Severe comorbidities'],
           'inclusion': ['Localized prostate cancer (T1-T2)', 'PSA <50 ng/mL', 'Adequate fitness for RP'],
           'nct': 'NCT00007644',
           'pmid': '22808955',
           'regimen_tested': 'Radical prostatectomy vs observation',
           'stage': 'localized_initial'},
 'PRESTO': {'biomarker_required': None,
            'citation': 'Aggarwal R et al. PRESTO/AFT-19. JCO 2023;41:3169-3181.',
            'endpoint_primary': 'PSA-PFS',
            'evidence_level': 'level_2_category_2A',
            'exclusion': ['Distant metastases on conventional imaging', 'Visceral mets'],
            'inclusion': ['BCR with PSA doubling time ≤9 months', 'ADT-naïve or short prior ADT', 'ECOG 0-1'],
            'nct': 'NCT03009981',
            'pmid': '37000748',
            'regimen_tested': 'ADT + apalutamide ± abiraterone (intensification) vs ADT alone',
            'stage': 'recurrence_bcr'},
 'PREVAIL': {'biomarker_required': None,
             'citation': 'Beer TM et al. PREVAIL. NEJM 2014;371:424-433.',
             'endpoint_primary': 'OS + rPFS (co-primary)',
             'evidence_level': 'level_1_category_1',
             'exclusion': ['Visceral mets', 'Seizure history', 'Severe cardiovascular disease'],
             'inclusion': ['Chemo-naïve asymptomatic/minimally symptomatic mCRPC', 'ECOG 0-1'],
             'nct': 'NCT01212991',
             'pmid': '24863011',
             'regimen_tested': 'Enzalutamide 160 mg vs placebo (chemo-naïve mCRPC)',
             'stage': 'm1_crpc'},
 'PROSPER': {'biomarker_required': None,
             'citation': 'Hussain M et al. PROSPER. NEJM 2018;378:2465-2474.',
             'endpoint_primary': 'MFS',
             'evidence_level': 'level_1_category_1',
             'exclusion': ['Distant metastases', 'Seizure history', 'Severe cardiovascular disease'],
             'inclusion': ['Non-metastatic CRPC (M0)',
                           'PSA doubling time ≤10 months',
                           'PSA ≥2 ng/mL on ADT',
                           'Castrate testosterone (<50 ng/dL)',
                           'ECOG 0-1'],
             'nct': 'NCT02003924',
             'pmid': '29949494',
             'regimen_tested': 'ADT + enzalutamide 160 mg vs ADT + placebo',
             'stage': 'm0_crpc'},
 'PROTECT': {'biomarker_required': None,
             'citation': 'Hamdy FC et al. PROTECT. NEJM 2016;375:1415-1424.',
             'endpoint_primary': 'Prostate cancer mortality (10-year)',
             'evidence_level': 'level_1_category_1',
             'exclusion': ['Locally advanced (T3-T4)', 'Metastases'],
             'inclusion': ['Localized prostate cancer (cT1-T2, N0M0)', 'PSA <20 ng/mL', 'Mostly Gleason 6, some 7'],
             'nct': 'NCT02044172',
             'pmid': '27626136',
             'regimen_tested': 'Active monitoring vs RP vs RT (Gleason 6 mostly)',
             'stage': 'localized_initial'},
 'PROfound': {'biomarker_required': 'HRR mutation (BRCA1/2/ATM cohort A; 12 genes cohort B)',
              'citation': 'de Bono J et al. PROfound. NEJM 2020;382:2091-2102.',
              'endpoint_primary': 'rPFS (Cohort A) + OS',
              'evidence_level': 'level_1_category_1',
              'exclusion': ['MDS/AML history', 'Active uncontrolled infection', 'Brain metastases'],
              'inclusion': ['mCRPC with progression on prior ARPI (abi or enza)',
                            'Qualifying HRR mutation: BRCA1, BRCA2, ATM (Cohort A) or 12 other HRR genes (Cohort B)',
                            'ECOG 0-2'],
              'nct': 'NCT02987543',
              'pmid': '32343890',
              'regimen_tested': 'Olaparib 300 mg BID vs ARPI switch (HRR-mutated mCRPC)',
              'stage': 'm1_crpc'},
 'PROpel': {'biomarker_required': None,
            'citation': 'Clarke NW et al. PROpel. NEJM Evid 2022;1:EVIDoa2200043.',
            'endpoint_primary': 'rPFS',
            'evidence_level': 'level_1_category_1',
            'exclusion': ['Prior systemic therapy for mCRPC', 'MDS/AML history', 'Severe hepatic impairment'],
            'inclusion': ['Newly diagnosed mCRPC (1st-line)', 'All-comers (HRR not required for entry)', 'ECOG 0-1'],
            'nct': 'NCT03732820',
            'pmid': '35513049',
            'regimen_tested': 'Olaparib + abiraterone vs abi + placebo (1L mCRPC, all-comers)',
            'stage': 'm1_crpc'},
 'PSMAfore': {'biomarker_required': 'PSMA-PET positive',
              'citation': 'Morris MJ et al. PSMAfore. JCO 2024;42(17_suppl):LBA5000.',
              'endpoint_primary': 'rPFS',
              'evidence_level': 'level_1_category_1',
              'exclusion': ['Prior taxane chemotherapy', 'PSMA-negative', 'Brain metastases'],
              'inclusion': ['PSMA-positive mCRPC after 1 prior ARPI',
                            'Chemo-naïve',
                            'ECOG 0-1',
                            'Adequate organ function'],
              'nct': 'NCT04689828',
              'pmid': '37866746',
              'regimen_tested': 'Lu-177-PSMA-617 vs ARPI switch (chemo-naïve mCRPC after 1 ARPI)',
              'stage': 'm1_crpc'},
 'RADICALS-RT': {'biomarker_required': None,
                 'citation': 'Parker CC et al. RADICALS-RT. Lancet 2020;396:1413-1421.',
                 'endpoint_primary': 'BCR-free survival',
                 'evidence_level': 'level_1_category_1',
                 'exclusion': ['Distant metastases', 'Persistent post-RP PSA'],
                 'inclusion': ['Post-RP patients with adverse features (positive margins, pT3, Gleason ≥7)',
                               'PSA <0.2 at randomization (adjuvant cohort) or ≤0.2 (salvage)'],
                 'nct': 'NCT00541047',
                 'pmid': '33002431',
                 'regimen_tested': 'Adjuvant RT vs early salvage RT after RP',
                 'stage': 'post_prostatectomy'},
 'RAVES': {'biomarker_required': None,
           'citation': 'Kneebone A et al. RAVES. Lancet Oncol 2020;21:1331-1340.',
           'endpoint_primary': 'BCR-free survival',
           'evidence_level': 'level_1_category_1',
           'exclusion': ['Distant mets', 'Persistent PSA'],
           'inclusion': ['Post-RP with adverse features (pT3a/b, positive margins, Gleason ≥7)',
                         'PSA <0.1 at randomization'],
           'nct': 'NCT00860652',
           'pmid': '33002432',
           'regimen_tested': 'Adjuvant RT vs early salvage RT after RP',
           'stage': 'post_prostatectomy'},
 'RTOG-9601': {'biomarker_required': None,
               'citation': 'Shipley WU et al. RTOG-9601. NEJM 2017;376:417-428.',
               'endpoint_primary': 'OS',
               'evidence_level': 'level_1_category_1',
               'exclusion': ['Distant metastases', 'PSA >4.0 (excluded as too high)'],
               'inclusion': ['BCR post-RP with PSA 0.2-4.0', 'pT2-T3 with margin status', 'Adequate organ function'],
               'nct': 'NCT00002874',
               'pmid': '28199825',
               'regimen_tested': 'Salvage RT + bicalutamide 150 mg/d x24 months vs RT + placebo',
               'stage': 'recurrence_bcr'},
 'SPARTAN': {'biomarker_required': None,
             'citation': 'Smith MR et al. SPARTAN. NEJM 2018;378:1408-1418.',
             'endpoint_primary': 'Metastasis-free survival (MFS)',
             'evidence_level': 'level_1_category_1',
             'exclusion': ['Distant metastases on bone scan/CT', 'History of seizure', 'Severe cardiovascular disease'],
             'inclusion': ['Non-metastatic CRPC (M0 by conventional imaging)',
                           'PSA doubling time ≤10 months',
                           'PSA ≥2 ng/mL during ADT',
                           'Castrate testosterone (<50 ng/dL)',
                           'ECOG 0-1'],
             'nct': 'NCT01946204',
             'pmid': '29420164',
             'regimen_tested': 'ADT + apalutamide 240 mg vs ADT + placebo',
             'stage': 'm0_crpc'},
 'SPCG-4': {'biomarker_required': None,
            'citation': 'Bill-Axelson A et al. SPCG-4. NEJM 2018;379:2319-2329 (long-term).',
            'endpoint_primary': 'OS (very long-term)',
            'evidence_level': 'level_1_category_1',
            'exclusion': ['Metastatic disease', 'Comorbidities limiting surgery'],
            'inclusion': ['Localized prostate cancer (T1-T2)', 'Age <75', 'Life expectancy >10 years'],
            'nct': 'Not registered (pre-registry era)',
            'pmid': '12646536',
            'regimen_tested': 'Radical prostatectomy vs watchful waiting',
            'stage': 'localized_initial'},
 'SPPORT': {'biomarker_required': None,
            'citation': 'Pollack A et al. SPPORT. Lancet 2022;399:1886-1901.',
            'endpoint_primary': 'Freedom from progression (5-year)',
            'evidence_level': 'level_1_category_1',
            'exclusion': ['Distant mets', 'Prior pelvic RT'],
            'inclusion': ['BCR post-RP with PSA ≥0.1', 'Adverse features (Gleason ≥8, pT3, margins+)'],
            'nct': 'NCT00567580',
            'pmid': '35569376',
            'regimen_tested': 'Salvage RT prostate bed + STAD ± pelvic LN RT',
            'stage': 'recurrence_bcr'},
 'STAMPEDE': {'biomarker_required': None,
              'citation': 'James ND et al. STAMPEDE. Lancet 2016;387:1163-1177.',
              'endpoint_primary': 'OS + failure-free survival',
              'evidence_level': 'level_1_category_1',
              'exclusion': ['Prior systemic therapy ≥12 weeks before', 'Significant cardiovascular disease'],
              'inclusion': ['Newly diagnosed metastatic, locally advanced, or node-positive prostate cancer',
                            'Fit for combination therapy',
                            'Adequate organ function'],
              'nct': 'NCT00268476',
              'pmid': '29384722',
              'regimen_tested': 'ADT + docetaxel + zoledronate (multiple arms tested)',
              'stage': 'mcspc',
              'subgroups': ['arm_g_RT_to_primary', 'arm_h_abiraterone', 'arm_c_docetaxel']},
 'SWOG-8794': {'biomarker_required': None,
               'citation': 'Thompson IM et al. SWOG-8794. JAMA 2006;296:2329-2335.',
               'endpoint_primary': 'OS + DFS',
               'evidence_level': 'level_1_category_1',
               'exclusion': ['Distant metastases', 'PSA persistence'],
               'inclusion': ['pT3 post-RP', 'PSA <0.4 ng/mL post-RP'],
               'nct': 'NCT00002709',
               'pmid': '16985183',
               'regimen_tested': 'Adjuvant RT vs observation (pT3 post-RP)',
               'stage': 'post_prostatectomy'},
 'TALAPRO-2': {'biomarker_required': 'HRR mutation for Cohort 2 (talazoparib labeled use)',
               'citation': 'Agarwal N et al. TALAPRO-2. Lancet 2023;402:291-303.',
               'endpoint_primary': 'rPFS',
               'evidence_level': 'level_1_category_1',
               'exclusion': ['MDS/AML', 'Prior PARP inhibitor', 'Brain metastases'],
               'inclusion': ['Newly diagnosed mCRPC (1st-line)',
                             'All-comers (Cohort 1) + HRR-deficient (Cohort 2)',
                             'ECOG 0-1'],
               'nct': 'NCT03395197',
               'pmid': '37086745',
               'regimen_tested': 'Talazoparib + enzalutamide vs enza + placebo (1L mCRPC)',
               'stage': 'm1_crpc'},
 'TAX-327': {'biomarker_required': None,
             'citation': 'Tannock IF et al. TAX-327. NEJM 2004;351:1502-1512.',
             'endpoint_primary': 'OS',
             'evidence_level': 'level_1_category_1',
             'exclusion': ['Prior cytotoxic chemotherapy', 'Severe cardiovascular disease'],
             'inclusion': ['Metastatic castration-resistant prostate cancer',
                           'ECOG 0-2',
                           'Adequate hepatic/renal function'],
             'nct': 'NCT00134524',
             'pmid': '15470213',
             'regimen_tested': 'Docetaxel 75 mg/m² q3w + prednisone vs mitoxantrone',
             'stage': 'm1_crpc'},
 'TITAN': {'biomarker_required': None,
           'citation': 'Chi KN et al. TITAN. NEJM 2019;381:13-24.',
           'endpoint_primary': 'OS + rPFS (co-primary)',
           'evidence_level': 'level_1_category_1',
           'exclusion': ['Brain metastases', 'History of seizure', 'Severe hepatic impairment'],
           'inclusion': ['Metastatic castration-sensitive prostate cancer', 'ECOG 0-1', 'Adequate organ function'],
           'nct': 'NCT02489318',
           'pmid': '31166680',
           'regimen_tested': 'ADT + apalutamide 240 mg vs ADT + placebo',
           'stage': 'mcspc',
           'subgroups': ['high_volume', 'low_volume', 'with_prior_docetaxel']},
 'TRITON-3': {'biomarker_required': 'BRCA1/BRCA2/ATM mutation',
              'citation': 'Fizazi K et al. TRITON3. NEJM 2023;388:719-732.',
              'endpoint_primary': 'Imaging-based PFS',
              'evidence_level': 'level_1_category_1',
              'exclusion': ['Prior PARP inhibitor', 'MDS/AML'],
              'inclusion': ['mCRPC progressing on 1 ARPI',
                            'BRCA1, BRCA2, or ATM mutation (germline or somatic)',
                            'ECOG 0-1',
                            'No prior chemo for mCRPC'],
              'nct': 'NCT02975934',
              'pmid': '36802571',
              'regimen_tested': 'Rucaparib 600 mg BID vs physician choice (BRCA+ mCRPC post-ARPI)',
              'stage': 'm1_crpc'},
 'TROPIC': {'biomarker_required': None,
            'citation': 'de Bono JS et al. TROPIC. Lancet 2010;376:1147-1154.',
            'endpoint_primary': 'OS',
            'evidence_level': 'level_1_category_1',
            'exclusion': ['Severe neuropathy ≥grade 2', 'Active infection requiring antibiotics', 'ANC <1500'],
            'inclusion': ['mCRPC with progression on/after docetaxel', 'ECOG 0-2', 'Adequate organ function'],
            'nct': 'NCT00417079',
            'pmid': '20888992',
            'regimen_tested': 'Cabazitaxel 25 mg/m² q3w + prednisone vs mitoxantrone (post-docetaxel)',
            'stage': 'm1_crpc'},
 'TheraP': {'biomarker_required': 'PSMA-PET positive (SUVmax ≥20)',
            'citation': 'Hofman MS et al. TheraP. Lancet 2021;397:797-804.',
            'endpoint_primary': 'PSA response (≥50% reduction)',
            'evidence_level': 'level_1_category_1',
            'exclusion': ['Discordant FDG-positive PSMA-negative lesions',
                          'Brain metastases',
                          'Inadequate organ function'],
            'inclusion': ['PSMA-positive mCRPC progressing post-docetaxel',
                          'PSMA SUVmax ≥20 in ≥1 lesion AND avidity > liver in all measurable lesions',
                          'ECOG 0-2'],
            'nct': 'NCT03392428',
            'pmid': '33581798',
            'regimen_tested': 'Lu-177-PSMA-617 6-8 GBq q6w x6 vs cabazitaxel',
            'stage': 'm1_crpc'},
 'VISION': {'biomarker_required': 'PSMA-PET positive (SUVmax > liver)',
            'citation': 'Sartor O et al. VISION. NEJM 2021;385:1091-1103.',
            'endpoint_primary': 'rPFS + OS (alternate primary)',
            'evidence_level': 'level_1_category_1',
            'exclusion': ['PSMA-negative disease',
                          'Untreated brain metastases',
                          'Diffuse marrow involvement (>50%)',
                          'GFR <30 mL/min'],
            'inclusion': ['PSMA-positive mCRPC (≥1 lesion with SUVmax > liver background)',
                          'Prior ≥1 ARPI AND ≥1 taxane chemotherapy',
                          'ECOG 0-2',
                          'Castrate testosterone'],
            'nct': 'NCT03511664',
            'pmid': '34161051',
            'regimen_tested': 'Lu-177-PSMA-617 7.4 GBq q6w x6 + standard of care vs SOC',
            'stage': 'm1_crpc'}}


def get_trial_criteria(trial_id: str) -> dict[str, Any]:
    return dict(TRIAL_CRITERIA_REGISTRY.get(str(trial_id or ""), {}))


def list_trial_ids() -> list[str]:
    return sorted(TRIAL_CRITERIA_REGISTRY.keys())


def list_trials_by_stage(stage: str) -> list[str]:
    token = str(stage or "").strip().lower()
    matching: list[str] = []
    for trial_id, criteria in TRIAL_CRITERIA_REGISTRY.items():
        stages = [str(item).lower() for item in criteria.get("stages", []) or criteria.get("disease_states", []) or []]
        if token and token in stages:
            matching.append(trial_id)
    return sorted(matching)


def list_trials_by_biomarker(biomarker_name: str) -> list[str]:
    token = str(biomarker_name or "").strip().upper()
    matching: list[str] = []
    for trial_id, criteria in TRIAL_CRITERIA_REGISTRY.items():
        biomarkers = criteria.get("biomarkers", []) or criteria.get("required_biomarkers", []) or []
        if any(str(item).upper() == token for item in biomarkers):
            matching.append(trial_id)
    return sorted(matching)


def get_total_trials_count() -> int:
    return len(TRIAL_CRITERIA_REGISTRY)


__all__ = [
    "TRIAL_CRITERIA_REGISTRY",
    "get_trial_criteria",
    "list_trial_ids",
    "list_trials_by_stage",
    "list_trials_by_biomarker",
    "get_total_trials_count",
]
