"""Faubot Agentic Loop — Proposal Generator (LXXXVIII).

Routes a `Gap` to the appropriate skill client + builds a `Proposal`
with concrete `proposed_changes` (file paths, content seeds, validation
checks).

Bootstrap LXXXVIII: este módulo es un STUB en modo Shadow — describe la
estructura de cambios sin invocar realmente las skills. Iteraciones
posteriores conectarán cada client a la skill bundled correspondiente
(docx/xlsx/pubmed/code-review).

API:
    proposal = generate_proposal_for_gap(gap)  # ProposalDraft
    skill_invoke_dry_run(proposal)              # → list[str] of changes that WOULD be made
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from prostanet.agentic.compliance_scorer import Gap

PROJECT_ROOT = Path(__file__).parent.parent.parent


@dataclass
class ProposalDraft:
    """Draft de cambio generado por proposal_generator."""
    gap: Gap
    skill_chain: list[str]  # e.g., ["docx", "fda-medtech-compliance-auditor"]
    proposed_artifact: str  # e.g., "regulatory/sops/SOP-DCG-001.docx"
    proposed_content_seed: str = ""  # frontmatter / template seed
    validation_checks: list[str] = field(default_factory=list)
    estimated_iterations_to_close: int = 1
    blocked_human: bool = False  # True si requires human signoff (e.g., prospective protocol)

    def to_dict(self) -> dict[str, Any]:
        return {
            "gap_kind": self.gap.kind,
            "gap_pillar": self.gap.pillar_id,
            "gap_severity": self.gap.severity,
            "skill_chain": self.skill_chain,
            "proposed_artifact": self.proposed_artifact,
            "proposed_content_seed_len": len(self.proposed_content_seed),
            "validation_checks": self.validation_checks,
            "estimated_iterations_to_close": self.estimated_iterations_to_close,
            "blocked_human": self.blocked_human,
        }


def generate_proposal_for_gap(gap: Gap) -> ProposalDraft:
    """Router principal: dispatch a la sub-función según gap.kind."""
    kind = gap.kind.split(":")[0]

    routers = {
        "regulatory_doc_missing": _route_regulatory_doc,
        "cds_criteria_yaml_missing": _route_cds_criteria,
        "cds_criteria_incomplete": _route_cds_criteria,
        "iec62304_class_unassigned": _route_iec62304_class,
        "iec62304_class_undocumented": _route_iec62304_class,
        "sop_missing": _route_sop,
        "qms_roster_missing": _route_qms_roster,
        "qms_roles_unassigned": _route_qms_roster,
        "part11_checklist_missing": _route_part11,
        "part11_control_missing": _route_part11,
        "iec62304_test_mapping_incomplete": _route_iec62304_test_mapping,
        "sbom_unpinned_dependencies": _route_sbom,
        "sbom_missing": _route_sbom,
        "sbom_incomplete": _route_sbom,
        "cve_critical_open": _route_cve,
        "cve_scan_tool_missing": _route_cve_tool,
        "sdp_missing": _route_sdp,
        "fmea_file_missing": _route_fmea,
        "fmea_entry_missing": _route_fmea,
        "fmea_mitigations_incomplete": _route_fmea,
        "tir57_addendum_missing": _route_tir57,
        "trial_evidence_missing": _route_trial_evidence,
        "retro_validation_missing": _route_retro_validation,
        "prospective_protocol_missing": _route_prospective_protocol,
        "prospective_data_incomplete": _route_prospective_data,
        "stride_threat_model_missing": _route_stride,
        "stride_threat_categories_incomplete": _route_stride,
        "disclosure_policy_missing": _route_disclosure,
        "vex_addendum_missing": _route_vex,
        "traceability_matrix_missing": _route_traceability,
        "traceability_row_missing": _route_traceability,
        "cr_log_missing": _route_cr_log,
        "design_input_baseline_unlocked": _route_design_baseline,
    }
    handler = routers.get(kind, _route_default)
    return handler(gap)


# ─── Per-kind routers ─────────────────────────────────────────────────────
def _route_regulatory_doc(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:fda-medtech-compliance-auditor", "anthropic-skills:docx"],
        proposed_artifact=gap.artifact_path or "regulatory/regulatory/<doc>.md",
        proposed_content_seed="# {doc_title}\n\nGenerated by Faubot LXXXVIII\n",
        validation_checks=["File exists", "Size > 100 bytes", "References NCCN/EAU/IMDRF"],
    )


def _route_cds_criteria(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:fda-medtech-compliance-auditor"],
        proposed_artifact="prostanet/regulatory/regulatory/cds_criteria.yaml",
        proposed_content_seed="# CDS criteria YAML — 4 criterios per FDA Final Guidance Sept 2022\n",
        validation_checks=["YAML parses", "Has 4 criteria entries", "Each criteria has met=true/false"],
    )


def _route_iec62304_class(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:fda-medtech-compliance-auditor"],
        proposed_artifact="prostanet/regulatory/regulatory/iec62304_class.md",
        proposed_content_seed="# IEC 62304 Class B/C assignment\n",
        validation_checks=["Document references IEC 62304:2006/AMD 1:2015", "Class A/B/C explicitly stated"],
    )


def _route_sop(gap: Gap) -> ProposalDraft:
    sop_id = gap.kind.split(":")[-1] if ":" in gap.kind else "SOP-XXX-NNN"
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:docx", "anthropic-skills:fda-medtech-compliance-auditor"],
        proposed_artifact=f"prostanet/regulatory/sops/{sop_id}.md",  # docx in next iter
        proposed_content_seed=f"# {sop_id}\n\n## Purpose\n## Scope\n## Procedure\n## Records\n## References\n",
        validation_checks=["File exists", "Has Purpose/Scope/Procedure sections", "References ISO 13485 + 21 CFR"],
    )


def _route_qms_roster(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:fda-medtech-compliance-auditor"],
        proposed_artifact="prostanet/regulatory/qms/roster.yaml",
        proposed_content_seed="# QMS Roles Roster\nquality_lead:\n  name: ...\n",
        validation_checks=["YAML parses", "Has quality_lead/software_lead/clinical_lead keys", "Each has name + email"],
        blocked_human=True,  # roles must be assigned by humans
    )


def _route_part11(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:fda-medtech-compliance-auditor"],
        proposed_artifact="prostanet/regulatory/qms/part11_checklist.yaml",
        proposed_content_seed="# 21 CFR Part 11 controls (8 controls)\n",
        validation_checks=["YAML parses", "Has 8 controls", "Each marked implemented=true/false"],
    )


def _route_iec62304_test_mapping(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:code-reviewer", "gate-validator"],
        proposed_artifact="tests/test_*.py (add @iec62304_phase decorator)",
        proposed_content_seed="# Add phase comment: # IEC 62304 §5.5 (Unit verification)\n",
        validation_checks=["IEC_PATTERN matches in test file", "phase number is valid (5.x or 5.x.y)"],
        estimated_iterations_to_close=10,  # one batch of tests per iteration
    )


def _route_sbom(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:code-reviewer"],
        proposed_artifact="prostanet/regulatory/security/sbom-cyclonedx.json",
        proposed_content_seed='{"bomFormat": "CycloneDX", "specVersion": "1.5", ...}',
        validation_checks=["JSON parses", "components[] non-empty", "Each component has version pinned"],
    )


def _route_cve(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:code-reviewer", "anthropic-skills:fda-medtech-compliance-auditor"],
        proposed_artifact="pyproject.toml + prostanet/regulatory/security/cve-remediation.md",
        proposed_content_seed="# CVE remediation log\n",
        validation_checks=["pip-audit reports 0 CRIT/HIGH after fix"],
    )


def _route_cve_tool(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:code-reviewer"],
        proposed_artifact="requirements-dev.txt (add pip-audit)",
        proposed_content_seed="pip-audit==2.7.0\n",
        validation_checks=["pip-audit installed", "Can run pip-audit --strict"],
    )


def _route_sdp(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:fda-medtech-compliance-auditor", "anthropic-skills:docx"],
        proposed_artifact="prostanet/regulatory/regulatory/sdp_software_development_plan.md",
        proposed_content_seed="# Software Development Plan (IEC 62304 §5.1)\n",
        validation_checks=["File >500 bytes", "References IEC 62304", "Defines lifecycle phases"],
    )


def _route_fmea(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:clinical-reports", "anthropic-skills:xlsx",
                      "anthropic-skills:healthcare-cdss-patterns"],
        proposed_artifact="prostanet/regulatory/risk/fmea-prostanet-2026.yaml",
        proposed_content_seed="# FMEA tabular per ISO 14971:2019\n",
        validation_checks=["YAML parses", "≥15 hazards", "Each has severity/occurrence/detectability/RPN"],
    )


def _route_tir57(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:fda-medtech-compliance-auditor"],
        proposed_artifact="prostanet/regulatory/risk/tir57_addendum.md",
        proposed_content_seed="# AAMI TIR57 Cybersecurity-Risk Coupling\n",
        validation_checks=["File >200 bytes", "References AAMI TIR57:2016"],
    )


def _route_trial_evidence(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:pubmed-database", "anthropic-skills:iterative-retrieval"],
        proposed_artifact="prostanet/shared/pivotal_gates_catalog/<gate>.yaml (add trial_refs[])",
        proposed_content_seed="trial_refs:\n  - PMID: 12345\n    NCT: NCT01234567\n    citation: ...\n",
        validation_checks=["Gate YAML has trial_refs[]", "Each ref has PMID + citation"],
        estimated_iterations_to_close=10,
    )


def _route_retro_validation(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:clinical-reports"],  # custom retro validator
        proposed_artifact="prostanet/regulatory/clinical/retro_validation_results.yaml",
        proposed_content_seed="# Retro AUC/PPV/NPV per gate over SQLite cohort\n",
        validation_checks=["YAML parses", "Each result has auc/ppv/npv", "Cohort N reported"],
        estimated_iterations_to_close=8,
    )


def _route_prospective_protocol(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:clinical-reports", "anthropic-skills:fda-medtech-compliance-auditor",
                      "anthropic-skills:docx"],
        proposed_artifact="prostanet/regulatory/clinical/protocol_prospective.md",
        proposed_content_seed="# Prospective Validation Protocol (DRAFT)\n",
        validation_checks=["File >1000 bytes", "Has hypothesis + design + endpoints", "Pending signature"],
        blocked_human=True,
        estimated_iterations_to_close=999,  # human-gated
    )


def _route_prospective_data(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=[],  # out-of-loop
        proposed_artifact="(out-of-loop · cohort enrollment)",
        proposed_content_seed="",
        validation_checks=[],
        blocked_human=True,
        estimated_iterations_to_close=999,
    )


def _route_stride(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:code-reviewer"],
        proposed_artifact="prostanet/regulatory/security/STRIDE-threat-model.md",
        proposed_content_seed="# STRIDE Threat Model\n## S — Spoofing\n## T — Tampering\n## R — Repudiation\n## I — Information Disclosure\n## D — Denial of Service\n## E — Elevation of Privilege\n",
        validation_checks=["File >500 bytes", "All 6 STRIDE categories addressed"],
    )


def _route_disclosure(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:fda-medtech-compliance-auditor"],
        proposed_artifact="SECURITY.md",
        proposed_content_seed="# Security Policy\n## Reporting a Vulnerability\n",
        validation_checks=["File >100 bytes", "Has reporting contact", "SLA defined"],
    )


def _route_vex(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:code-reviewer"],
        proposed_artifact="prostanet/regulatory/security/vex.json",
        proposed_content_seed='{"vulnerabilities": []}',
        validation_checks=["JSON parses"],
    )


def _route_traceability(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:xlsx", "anthropic-skills:fda-medtech-compliance-auditor"],
        proposed_artifact="prostanet/regulatory/dhf/traceability_matrix.yaml",
        proposed_content_seed="# DHF Traceability: req_id, code_path, test_id, mitigation_id\n",
        validation_checks=["YAML parses", "≥107 rows", "Each row has 4 required cols filled"],
    )


def _route_cr_log(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=["anthropic-skills:fda-medtech-compliance-auditor"],
        proposed_artifact="prostanet/regulatory/dhf/change_request_log.yaml",
        proposed_content_seed="# Change Request Log\n",
        validation_checks=["File >50 bytes", "Has change_requests[] list"],
    )


def _route_design_baseline(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=[],
        proposed_artifact="prostanet/regulatory/dhf/design_input_baseline.lock",
        proposed_content_seed="FAUBOT_RELEASE bootstrap baseline",
        validation_checks=["File exists"],
    )


def _route_default(gap: Gap) -> ProposalDraft:
    return ProposalDraft(
        gap=gap,
        skill_chain=[],
        proposed_artifact="(unknown gap kind · manual review needed)",
        proposed_content_seed="",
        validation_checks=[],
    )


def skill_invoke_dry_run(draft: ProposalDraft) -> list[str]:
    """Returns lista de cambios que el skill chain HARÍA si fueran invoked.

    En LXXXVIII bootstrap esto es DRY-RUN — describe lo que ocurriría sin
    invocar las skills. Iteraciones LXXXIX+ conectan cada skill real.
    """
    actions = []
    actions.append(f"[1/3] Read gap context (pillar {draft.gap.pillar_id}, severity {draft.gap.severity})")
    if draft.skill_chain:
        actions.append(f"[2/3] Invoke skills: {' → '.join(draft.skill_chain)}")
        actions.append(f"[3/3] Write artifact: {draft.proposed_artifact}")
    else:
        actions.append("[2/3] No skill chain (manual review or out-of-loop)")
    if draft.blocked_human:
        actions.append("[!] BLOCKED: human signoff required")
    return actions
