# -*- coding: utf-8 -*-
"""Auditoría #14 — Catálogo canónico de pacientes insignia por estudio pivotal.

Cada entrada describe el "paciente insignia" del trial: el perfil clínico
publicado en el ensayo pivotal (criterios de inclusión + características
medianas), las comorbilidades relevantes, los efectos adversos clave y las
contraindicaciones que ProstaNet debe poder reconocer y procesar.

Este registro sirve como espejo de auditoría para `trial_matching_engine.py`
y como input estable para los tests de cobertura clínica
(`tests/test_pivotal_trials_audit.py`).

Cada `PivotalPatientProfile` cumple cuatro propósitos:

1. **Diagnóstico**: el campo ``payload`` es directamente alimentable a
   ``StateClassifierService`` y produce el ``expected_state`` declarado.
2. **Elegibilidad**: el ``trial_code`` debe matchear positivamente vía
   ``match_patient_to_trials(payload)``.
3. **Comorbilidades / AEs**: el campo ``comorbidity_signals`` lista las
   señales que el motor de selección ARPI / DDI debe ver y reaccionar.
4. **Contraindicaciones**: ``contraindication_signals`` lista los hard-blocks
   o cautions que deben evitar prescribir el régimen del trial al paciente
   insignia cuando aplica (p. ej. seizure history para AFFIRM/PREVAIL).

Las referencias bibliográficas se conservan en `evidence_registry/data.py` y
en los `evidence_tags` del catálogo del trial-matching engine.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class PivotalPatientProfile:
    """Snapshot canónico del paciente insignia del trial."""

    trial_code: str
    nct_id: str
    expected_state: str
    expected_treatment_keywords: tuple[str, ...]
    payload: dict[str, Any]
    comorbidity_signals: tuple[str, ...] = field(default_factory=tuple)
    adverse_event_signals: tuple[str, ...] = field(default_factory=tuple)
    contraindication_signals: tuple[str, ...] = field(default_factory=tuple)
    notes: str = ""


# ── Pacientes insignia (36 trials) ─────────────────────────────────────


PIVOTAL_PATIENT_PROFILES: tuple[PivotalPatientProfile, ...] = (
    PivotalPatientProfile(
        trial_code="RADICALS-RT",
        nct_id="NCT00541047",
        expected_state="post_prostatectomy",
        expected_treatment_keywords=("radioterapia", "salvage", "rt"),
        payload={
            "age": 65,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "prior_prostatectomy": 1,
            "psa_postop": 0.05,
            "psa": 0.05,
            "pT_stage": "pT3a",
            "pathological_t_stage": "pT3a",
            "surgical_margin_status": "positive",
            "adverse_pathology": 1,
            "gleason_primary": 4,
            "gleason_secondary": 3,
            "isup_grade": 3,
            "metastasis_site": "M0",
            "early_salvage_window": 1,
        },
        comorbidity_signals=(),
        adverse_event_signals=("late_rt_toxicity_gi", "late_rt_toxicity_gu"),
        contraindication_signals=("active_inflammatory_bowel_disease",),
        notes="Patología adversa pT3a R1; salvage temprano no inferior a adyuvante.",
    ),
    PivotalPatientProfile(
        trial_code="EMBARK",
        nct_id="NCT02319837",
        expected_state="recurrence_bcr",
        expected_treatment_keywords=("enzalutamida", "leuprolide", "embark"),
        payload={
            "age": 69,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "prior_prostatectomy": 1,
            "psa_current": 5.0,
            "psa_postop": 5.0,
            "psa_doubling_time_months": 8.5,
            "metastasis_site": "M0",
            "bcr_confirmed": 1,
            "bcr2": 1,
        },
        comorbidity_signals=("hypertension",),
        adverse_event_signals=("hot_flashes", "fatigue", "hypertension", "falls"),
        contraindication_signals=("severe_seizure_history",),
        notes="BCR alto-riesgo PSADT 8.5m, M0 confirmado.",
    ),
    PivotalPatientProfile(
        trial_code="PRESTO",
        nct_id="NCT03009981",
        expected_state="recurrence_bcr",
        expected_treatment_keywords=("apalutamida", "abiraterona", "adt"),
        payload={
            "age": 68,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "prior_prostatectomy": 1,
            "prior_secondary_rt": 1,
            "psa_current": 4.2,
            "psa_postop": 4.2,
            "psa_doubling_time_months": 7.0,
            "psadt_months": 7.0,
            "metastasis_site": "M0",
            "bcr_confirmed": 1,
            # Auditoría insignia — activa la rama BCR2 N0M0 + apalutamide_experimental
            # (recurrence_bcr/rules_nccn.py:36-43). Sin `bcr2` + `conventional_imaging_m0`
            # el caso cae en la rama genérica "Post-RP recurrence" que solo emite
            # salvage RT y nunca surface apalutamida/abiraterona intensificada (PRESTO
            # AFT-19, Aggarwal JCO 2023;41:3253: PSADT ≤9 m post-local-therapy).
            "bcr2": 1,
            "conventional_imaging_m0": 1,
            "imaging_negative": 1,
        },
        comorbidity_signals=("rash_history",),
        adverse_event_signals=("rash", "hypothyroidism", "fatigue", "hot_flashes"),
        contraindication_signals=("severe_hepatic_impairment",),
        notes="BCR2 PSADT corto post-RP+SRT; apalutamida ± abiraterona (PRESTO).",
    ),
    PivotalPatientProfile(
        trial_code="CHAARTED",
        nct_id="NCT00309985",
        expected_state="mcspc_high_volume",
        expected_treatment_keywords=("docetaxel", "adt"),
        payload={
            "age": 63,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "metastasis_site": "Bone, visceral",
            "metachronous_metastasis": "0",
            "bone_lesion_count": 6,
            "bone_lesions_outside_axial": 1,
            "visceral_disease": 1,
            "docetaxel_fit": 1,
            "performance_status_driver": "cancer_related",
            "gleason_primary": 4,
            "gleason_secondary": 4,
            "isup_grade": 4,
            "psa": 80.0,
        },
        comorbidity_signals=("neuropathy_baseline",),
        adverse_event_signals=("neutropenia", "neuropathy_grade2", "fatigue"),
        contraindication_signals=("severe_neuropathy_grade3", "neutropenia_grade4_ongoing"),
        notes="mHSPC alto volumen fit; ADT + docetaxel pivote OS +13.6m.",
    ),
    PivotalPatientProfile(
        trial_code="LATITUDE",
        nct_id="NCT01715285",
        expected_state="mcspc_high_volume",
        expected_treatment_keywords=("abiraterona", "prednisona", "adt"),
        payload={
            "age": 67,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "metastasis_site": "Bone, visceral",
            "metachronous_metastasis": "0",
            "gleason_primary": 4,
            "gleason_secondary": 5,
            "isup_grade": 5,
            "gleason_total": 9,
            "bone_lesion_count": 5,
            "visceral_disease": 1,
            "psa": 50.0,
            "docetaxel_fit": 0,
        },
        comorbidity_signals=("hypertension", "hypokalemia_risk"),
        adverse_event_signals=("hypertension", "hypokalemia", "hepatic_aes", "fluid_retention"),
        contraindication_signals=(
            "child_pugh_b_or_c",
            "uncontrolled_hypertension",
            "severe_heart_failure_nyha_iii_iv",
        ),
        notes="mHSPC LATITUDE: ≥2 factores de alto riesgo; abiraterona + ADT.",
    ),
    PivotalPatientProfile(
        trial_code="STAMPEDE",
        nct_id="NCT00268476",
        expected_state="mcspc_high_volume",
        expected_treatment_keywords=("docetaxel", "abiraterona", "rt"),
        payload={
            "age": 65,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "metastasis_site": "Bone",
            "metachronous_metastasis": "0",
            "bone_lesion_count": 4,
            "bone_lesions_outside_axial": 1,
            "docetaxel_fit": 1,
            "performance_status_driver": "cancer_related",
            "gleason_primary": 4,
            "gleason_secondary": 4,
            "isup_grade": 4,
            "psa": 60.0,
        },
        comorbidity_signals=(),
        adverse_event_signals=("neutropenia", "fatigue", "hot_flashes"),
        contraindication_signals=("severe_hepatic_impairment", "severe_heart_failure_nyha_iii_iv"),
        notes="Plataforma multi-arm; backbone STAMPEDE (G/H) trazable.",
    ),
    PivotalPatientProfile(
        trial_code="ENZAMET",
        nct_id="NCT02446405",
        expected_state="mcspc_high_volume",
        expected_treatment_keywords=("enzalutamida", "adt"),
        payload={
            "age": 68,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "metastasis_site": "Bone, visceral",
            "metachronous_metastasis": "0",
            "bone_lesion_count": 5,
            "visceral_disease": 1,
            "docetaxel_fit": 1,
            "performance_status_driver": "cancer_related",
            "psa": 40.0,
        },
        comorbidity_signals=("falls_risk",),
        adverse_event_signals=("fatigue", "falls", "qtc_prolongation"),
        contraindication_signals=("severe_seizure_history",),
        notes="mHSPC alto volumen; ENZAMET admite docetaxel concurrente.",
    ),
    PivotalPatientProfile(
        trial_code="ARCHES",
        nct_id="NCT02677896",
        expected_state="mcspc_high_volume",
        expected_treatment_keywords=("enzalutamida", "adt"),
        payload={
            "age": 70,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "metastasis_site": "Bone",
            "metachronous_metastasis": "0",
            "bone_lesion_count": 5,
            "bone_lesions_outside_axial": 1,
            "prior_docetaxel": 1,
            "psa": 35.0,
            "docetaxel_fit": 0,
        },
        comorbidity_signals=("hypertension",),
        adverse_event_signals=("fatigue", "hypertension", "fractures"),
        contraindication_signals=("severe_seizure_history",),
        notes="ARCHES admite docetaxel previo + ADT + enzalutamida.",
    ),
    PivotalPatientProfile(
        trial_code="TITAN",
        nct_id="NCT02489318",
        expected_state="mcspc_high_volume",
        expected_treatment_keywords=("apalutamida", "adt"),
        payload={
            "age": 68,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "metastasis_site": "Bone, visceral",
            "metachronous_metastasis": "0",
            "bone_lesion_count": 5,
            "visceral_disease": 1,
            "prior_docetaxel": 0,
            "psa": 35.0,
            "docetaxel_fit": 0,
        },
        comorbidity_signals=("rash_history", "hypothyroidism"),
        adverse_event_signals=("rash", "hypothyroidism", "fatigue", "falls"),
        contraindication_signals=("severe_seizure_history",),
        notes="TITAN evaluó apalutamida en todo el espectro mHSPC.",
    ),
    PivotalPatientProfile(
        trial_code="PEACE-1",
        nct_id="NCT01957436",
        expected_state="mcspc_high_volume",
        expected_treatment_keywords=("triplete", "abiraterona", "docetaxel"),
        payload={
            "age": 64,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "metastasis_site": "Bone, visceral",
            "metachronous_metastasis": "0",
            "bone_lesion_count": 6,
            "bone_lesions_outside_axial": 1,
            "visceral_disease": 1,
            "docetaxel_fit": 1,
            "performance_status_driver": "cancer_related",
            "psa": 100.0,
        },
        comorbidity_signals=("hypertension",),
        adverse_event_signals=(
            "neutropenia",
            "hypertension",
            "hepatic_aes",
            "fluid_retention",
        ),
        contraindication_signals=(
            "child_pugh_b_or_c",
            "severe_heart_failure_nyha_iii_iv",
            "uncontrolled_hypertension",
        ),
        notes="mHSPC alto volumen sincrónico; triplete vs ADT + abiraterona.",
    ),
    PivotalPatientProfile(
        trial_code="ARASENS",
        nct_id="NCT02799602",
        expected_state="mcspc_high_volume",
        expected_treatment_keywords=("triplete", "darolutamida", "docetaxel"),
        payload={
            "age": 63,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "metastasis_site": "Bone, visceral",
            "metachronous_metastasis": "0",
            "bone_lesion_count": 7,
            "bone_lesions_outside_axial": 1,
            "visceral_disease": 1,
            "docetaxel_fit": 1,
            "performance_status_driver": "cancer_related",
            "psa": 90.0,
        },
        comorbidity_signals=(),
        adverse_event_signals=("neutropenia", "fatigue", "rash"),
        contraindication_signals=("ecog_2_or_more",),
        notes="ARASENS triplete; ECOG 0-1 obligatorio.",
    ),
    PivotalPatientProfile(
        trial_code="ARANOTE",
        nct_id="NCT04736199",
        expected_state="mcspc_low_volume_sync_oligo",
        expected_treatment_keywords=("darolutamida", "adt"),
        payload={
            "age": 72,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "metastasis_site": "Bone",
            "metachronous_metastasis": "0",
            "bone_lesion_count": 2,
            "docetaxel_fit": 0,
            "psa": 18.0,
        },
        comorbidity_signals=("frailty_grade1",),
        adverse_event_signals=("fatigue", "rash", "fractures"),
        contraindication_signals=(
            "severe_hepatic_impairment",
            "prior_arpi_exposure_mhspc",
        ),
        notes="ARANOTE doblete sin chemo — pivote para frágil/elderly mHSPC. CI: hepatopatía severa Child-Pugh C; prior ARPI excluido del trial (Saad Lancet Oncol 2024;25:1422).",
    ),
    PivotalPatientProfile(
        trial_code="AMPLITUDE",
        nct_id="NCT04497844",
        expected_state="mcspc_high_volume",
        expected_treatment_keywords=("niraparib", "abiraterona"),
        payload={
            "age": 65,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "metastasis_site": "Bone, visceral",
            "metachronous_metastasis": "0",
            "bone_lesion_count": 5,
            "visceral_disease": 1,
            "germline_pathogenic_variant": "BRCA2",
            "hrr_positive": 1,
            "brca_pathway": 1,
            "biomarker_source": "ctDNA",
            # Auditoría #15 insignia — activa prefer_akeega (mcspc_high_volume/rules_nccn.py:38).
            # Sin estos cuatro campos el régimen AKEEGA (niraparib + abiraterona) NO se emite,
            # incluso con `germline_pathogenic_variant=BRCA2`, porque `molecular_traceable`
            # exige también origen del BRCA2 y metadatos del ensayo molecular (fuente+fecha).
            "brca2_status": "Positivo",
            "brca2_origin": "germline",
            "molecular_assay_source": "ctDNA",
            "molecular_assay_date": "2025-01-10",
            "psa": 55.0,
        },
        comorbidity_signals=("anemia_baseline",),
        adverse_event_signals=("anemia", "thrombocytopenia", "fatigue", "hypertension"),
        contraindication_signals=("active_marrow_failure", "severe_hepatic_impairment"),
        notes="AMPLITUDE BRCA+ enriquecido — niraparib + abiraterona en mHSPC; requiere origen BRCA2 y assay metadata para activar AKEEGA.",
    ),
    PivotalPatientProfile(
        trial_code="SPARTAN",
        nct_id="NCT01946204",
        expected_state="m0_crpc",
        expected_treatment_keywords=("apalutamida",),
        payload={
            "age": 74,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "castrate_testosterone_confirmed": 1,
            "imaging_negative": 1,
            "current_adt_context": "medical_adt_continuous",
            "progression_pattern": "biochemical_only",
            "conventional_imaging_status": "M0",
            "conventional_imaging_modality": "CT + bone scan",
            "psa_doubling_time_months": 4.3,
            "psadt_months": 4.3,
        },
        comorbidity_signals=("falls_risk", "rash_history"),
        adverse_event_signals=("rash", "hypothyroidism", "falls", "fractures"),
        contraindication_signals=("severe_seizure_history",),
        notes="SPARTAN nmCRPC PSADT 4.3m mediano.",
    ),
    PivotalPatientProfile(
        trial_code="PROSPER",
        nct_id="NCT02003924",
        expected_state="m0_crpc",
        expected_treatment_keywords=("enzalutamida",),
        payload={
            "age": 74,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "castrate_testosterone_confirmed": 1,
            "imaging_negative": 1,
            "current_adt_context": "medical_adt_continuous",
            "progression_pattern": "biochemical_only",
            "conventional_imaging_status": "M0",
            "conventional_imaging_modality": "CT + bone scan",
            "psa_doubling_time_months": 3.8,
            "psadt_months": 3.8,
        },
        comorbidity_signals=("falls_risk",),
        adverse_event_signals=("fatigue", "falls", "qtc_prolongation"),
        contraindication_signals=("severe_seizure_history",),
        notes="PROSPER nmCRPC PSADT 3.8m mediano; falls risk relevante.",
    ),
    PivotalPatientProfile(
        trial_code="ARAMIS",
        nct_id="NCT02200614",
        expected_state="m0_crpc",
        expected_treatment_keywords=("darolutamida",),
        payload={
            "age": 74,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "castrate_testosterone_confirmed": 1,
            "imaging_negative": 1,
            "current_adt_context": "medical_adt_continuous",
            "progression_pattern": "biochemical_only",
            "conventional_imaging_status": "M0",
            "conventional_imaging_modality": "CT + bone scan",
            "psa_doubling_time_months": 4.4,
            "psadt_months": 4.4,
            "comorbidity_seizure": 0,
        },
        comorbidity_signals=("seizure_predisposition",),
        adverse_event_signals=("fatigue", "rash"),
        contraindication_signals=(
            "severe_hepatic_impairment",
            "darolutamide_hypersensitivity",
        ),
        notes="ARAMIS nmCRPC; perfil CNS preferido (menor pase BBB) — apto para predisposición convulsiva. CI: hepatopatía severa Child-Pugh C; hipersensibilidad conocida (Fizazi NEJM 2019;380:1235).",
    ),
    PivotalPatientProfile(
        trial_code="TAX-327",
        nct_id="NCT00134056",
        expected_state="m1_crpc",
        expected_treatment_keywords=("docetaxel", "prednisona"),
        payload={
            "age": 68,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "first_line",
            "prior_docetaxel": 0,
            "docetaxel_fit": 1,
            "performance_status_driver": "cancer_related",
        },
        comorbidity_signals=("neuropathy_baseline",),
        adverse_event_signals=("neutropenia", "neuropathy", "fatigue", "alopecia"),
        contraindication_signals=("severe_neuropathy_grade3", "neutropenia_grade4_ongoing"),
        notes="TAX-327 fundación docetaxel mCRPC 1L.",
    ),
    PivotalPatientProfile(
        trial_code="TROPIC",
        nct_id="NCT00417079",
        expected_state="m1_crpc",
        expected_treatment_keywords=("cabazitaxel", "prednisona"),
        payload={
            "age": 67,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "post_taxane",
            "prior_docetaxel": 1,
            "prior_taxane": 1,
            "docetaxel_fit": 1,
            "performance_status_driver": "cancer_related",
        },
        comorbidity_signals=("anemia_baseline",),
        adverse_event_signals=("neutropenia_febril", "diarrea", "fatiga"),
        contraindication_signals=("hypersensitivity_polysorbate", "severe_neutropenia_grade4"),
        notes="TROPIC cabazitaxel post-docetaxel.",
    ),
    PivotalPatientProfile(
        trial_code="CARD",
        nct_id="NCT02485691",
        expected_state="m1_crpc",
        expected_treatment_keywords=("cabazitaxel",),
        payload={
            "age": 70,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "post_taxane",
            "prior_docetaxel": 1,
            "prior_arpi": 1,
            "prior_arpi_progression_months": 8,
            "docetaxel_fit": 1,
            "performance_status_driver": "cancer_related",
        },
        comorbidity_signals=("anemia_baseline",),
        adverse_event_signals=("neutropenia_febril", "diarrea"),
        contraindication_signals=("severe_neutropenia_grade4",),
        notes="CARD: progresión <12m a ARPI + post-docetaxel — cabazitaxel > ARPI switch.",
    ),
    PivotalPatientProfile(
        trial_code="COU-AA-301",
        nct_id="NCT00638690",
        expected_state="m1_crpc",
        expected_treatment_keywords=("abiraterona", "prednisona"),
        payload={
            "age": 69,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "post_taxane",
            "prior_docetaxel": 1,
            "pain_status": "moderate",
        },
        comorbidity_signals=("hypertension",),
        adverse_event_signals=("hypertension", "hypokalemia", "hepatic_aes", "fluid_retention"),
        contraindication_signals=(
            "child_pugh_b_or_c",
            "uncontrolled_hypertension",
            "severe_heart_failure_nyha_iii_iv",
        ),
        notes="COU-AA-301 abiraterona post-docetaxel sintomático.",
    ),
    PivotalPatientProfile(
        trial_code="COU-AA-302",
        nct_id="NCT00887198",
        expected_state="m1_crpc",
        expected_treatment_keywords=("abiraterona", "prednisona"),
        payload={
            "age": 71,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "first_line",
            "prior_docetaxel": 0,
            "pain_status": "minimal",
        },
        comorbidity_signals=("hypertension",),
        adverse_event_signals=("hypertension", "hypokalemia", "hepatic_aes", "fluid_retention"),
        contraindication_signals=(
            "child_pugh_b_or_c",
            "uncontrolled_hypertension",
            "severe_heart_failure_nyha_iii_iv",
        ),
        notes="COU-AA-302 abiraterona pre-chemo asintomático/leve.",
    ),
    PivotalPatientProfile(
        trial_code="AFFIRM",
        nct_id="NCT00974311",
        expected_state="m1_crpc",
        expected_treatment_keywords=("enzalutamida",),
        payload={
            "age": 69,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "post_taxane",
            "prior_docetaxel": 1,
            "comorbidity_seizure": 0,
            "seizure_history": 0,
        },
        comorbidity_signals=("falls_risk",),
        adverse_event_signals=("fatigue", "falls", "headache"),
        contraindication_signals=("severe_seizure_history",),
        notes="AFFIRM enzalutamida post-docetaxel; excluyó historia de convulsiones.",
    ),
    PivotalPatientProfile(
        trial_code="PREVAIL",
        nct_id="NCT01212991",
        expected_state="m1_crpc",
        expected_treatment_keywords=("enzalutamida",),
        payload={
            "age": 71,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "first_line",
            "prior_docetaxel": 0,
            "pain_status": "minimal",
            "comorbidity_seizure": 0,
            "seizure_history": 0,
        },
        comorbidity_signals=("falls_risk",),
        adverse_event_signals=("fatigue", "falls", "headache"),
        contraindication_signals=("severe_seizure_history",),
        notes="PREVAIL enzalutamida pre-chemo asintomático.",
    ),
    PivotalPatientProfile(
        trial_code="ALSYMPCA",
        nct_id="NCT00699751",
        expected_state="m1_crpc",
        expected_treatment_keywords=("ra-223", "radio", "rádio"),
        payload={
            "age": 72,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "later_line",
            "bone_lesion_count": 6,
            "bone_only_disease": 1,
            "symptomatic_bone_only": 1,
            "visceral_disease": 0,
        },
        comorbidity_signals=("anemia_baseline",),
        adverse_event_signals=("thrombocytopenia", "anemia", "diarrea"),
        contraindication_signals=("visceral_metastases", "concomitant_abiraterone_prednisone"),
        notes="ALSYMPCA Ra-223 mCRPC óseo sintomático sin viscerales.",
    ),
    PivotalPatientProfile(
        trial_code="VISION",
        nct_id="NCT03511664",
        expected_state="m1_crpc",
        expected_treatment_keywords=("lutecio", "lu-177", "psma", "pluvicto"),
        payload={
            "age": 70,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "post_taxane",
            "prior_arpi": 1,
            "prior_docetaxel": 1,
            "prior_taxane": 1,
            "psma_positive": 1,
            "psma_lesion_suvmax_minimum": 18.0,
            "psma_suvmean_liver": 6.5,
            "psma_negative_dominant_lesions": 0,
        },
        comorbidity_signals=("renal_dysfunction_mild",),
        adverse_event_signals=("xerostomia", "fatigue", "anemia", "trombocitopenia"),
        contraindication_signals=("severe_renal_failure_egfr_lt_30", "severe_marrow_failure"),
        notes="VISION mCRPC PSMA+ post-ARPI + post-taxano.",
    ),
    PivotalPatientProfile(
        trial_code="PSMAfore",
        nct_id="NCT04689828",
        expected_state="m1_crpc",
        expected_treatment_keywords=("lutecio", "lu-177", "psma", "pluvicto"),
        payload={
            "age": 71,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "first_line",
            "prior_arpi": 1,
            "prior_docetaxel": 0,
            "prior_taxane": 0,
            "chemotherapy_delay_candidate": 1,
            "psma_positive": 1,
            "psma_lesion_suvmax_minimum": 16.0,
            "psma_suvmean_liver": 6.0,
            "psma_negative_dominant_lesions": 0,
        },
        comorbidity_signals=("renal_dysfunction_mild",),
        adverse_event_signals=("xerostomia", "fatigue"),
        contraindication_signals=("severe_renal_failure_egfr_lt_30",),
        notes="PSMAfore mCRPC PSMA+ pre-taxano post-ARPI.",
    ),
    PivotalPatientProfile(
        trial_code="TheraP",
        nct_id="NCT03392428",
        expected_state="m1_crpc",
        expected_treatment_keywords=("lutecio", "lu-177", "psma", "pluvicto"),
        payload={
            "age": 71,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "post_taxane",
            "prior_docetaxel": 1,
            "prior_taxane": 1,
            "psma_positive": 1,
            "psma_lesion_suvmax_minimum": 22.0,
            "psma_suvmean_liver": 5.5,
            "psma_negative_dominant_lesions": 0,
        },
        comorbidity_signals=("anemia_baseline",),
        adverse_event_signals=("xerostomia", "trombocitopenia", "diarrea"),
        contraindication_signals=("severe_marrow_failure", "psma_negative_dominant_lesions"),
        notes="TheraP exigió SUVmax ≥20 en al menos una lesión índice.",
    ),
    PivotalPatientProfile(
        trial_code="PEACE-3",
        nct_id="NCT02194842",
        expected_state="m1_crpc",
        expected_treatment_keywords=("ra-223", "radio", "enzalutamida"),
        payload={
            "age": 72,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "first_line",
            "bone_lesion_count": 5,
            "bone_only_disease": 1,
            "visceral_disease": 0,
            "prior_arpi": 0,
            "denosumab_prophylaxis": 1,
            "bone_modifying_agent": "denosumab",
        },
        comorbidity_signals=("osteopenia",),
        adverse_event_signals=("fractures", "anemia", "fatigue"),
        contraindication_signals=(
            "concomitant_abiraterone_prednisone",
            "no_bone_protective_agent",
        ),
        notes="PEACE-3 Ra-223 + enzalutamida con profilaxis ósea obligatoria.",
    ),
    PivotalPatientProfile(
        trial_code="PROfound",
        nct_id="NCT02987543",
        expected_state="m1_crpc",
        expected_treatment_keywords=("olaparib",),
        payload={
            "age": 67,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "post_arpi",
            "prior_arpi": 1,
            "germline_pathogenic_variant": "BRCA2",
            "hrr_positive": 1,
        },
        comorbidity_signals=("anemia_baseline",),
        adverse_event_signals=("anemia", "thromboembolism", "nausea"),
        contraindication_signals=("severe_marrow_failure",),
        notes="PROfound olaparib HRR+ post-ARPI.",
    ),
    PivotalPatientProfile(
        trial_code="PROpel",
        nct_id="NCT03732820",
        expected_state="m1_crpc",
        expected_treatment_keywords=("olaparib", "abiraterona"),
        payload={
            "age": 69,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "first_line",
            "prior_arpi": 0,
            "prior_abiraterone": 0,
        },
        comorbidity_signals=("hypertension",),
        adverse_event_signals=("anemia", "hypertension", "hypokalemia", "fatigue"),
        contraindication_signals=("child_pugh_b_or_c", "severe_heart_failure_nyha_iii_iv"),
        notes="PROpel mCRPC 1L sin ARPI previo — olaparib + abiraterona.",
    ),
    PivotalPatientProfile(
        trial_code="MAGNITUDE",
        nct_id="NCT03748641",
        expected_state="m1_crpc",
        expected_treatment_keywords=("niraparib", "abiraterona"),
        payload={
            "age": 67,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "first_line",
            "prior_abiraterone": 0,
            "germline_pathogenic_variant": "BRCA2",
            "brca_pathway": 1,
            # Auditoría #15 insignia — activa biomarker_traceable (m1_crpc/service.py:66).
            # Sin `biomarker_source` + `hrr_gene` el bloque
            # `Niraparib + Abiraterone` en service.py:234-241 queda latente y el test
            # de keywords pasaría sólo por match parcial con "abiraterona".
            "biomarker_source": "Tejido tumoral",
            "hrr_gene": "BRCA2",
            "molecular_report_date": "2025-02-15",
            "brca2_origin": "germline",
        },
        comorbidity_signals=("anemia_baseline",),
        adverse_event_signals=("anemia", "thrombocytopenia", "hypertension"),
        contraindication_signals=("severe_marrow_failure",),
        notes="MAGNITUDE mCRPC 1L BRCA+ sin abiraterona previa; biomarker_source + hrr_gene requeridos para surface AKEEGA/niraparib.",
    ),
    PivotalPatientProfile(
        trial_code="TALAPRO-2",
        nct_id="NCT03395197",
        expected_state="m1_crpc",
        expected_treatment_keywords=("talazoparib", "enzalutamida"),
        payload={
            "age": 68,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "first_line",
            "prior_arpi": 0,
            "prior_enzalutamide": 0,
            "germline_pathogenic_variant": "BRCA2",
            "hrr_positive": 1,
        },
        comorbidity_signals=("anemia_baseline",),
        adverse_event_signals=("anemia", "neutropenia", "fatigue"),
        contraindication_signals=("severe_marrow_failure",),
        notes="TALAPRO-2 talazoparib + enzalutamida; HRR+ con beneficio primario.",
    ),
    PivotalPatientProfile(
        trial_code="TRITON-3",
        nct_id="NCT02975934",
        expected_state="m1_crpc",
        expected_treatment_keywords=("rucaparib",),
        payload={
            "age": 69,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "post_arpi",
            "prior_arpi": 1,
            "germline_pathogenic_variant": "BRCA2",
            "brca_pathway": 1,
            "hrr_positive": 1,
        },
        comorbidity_signals=("anemia_baseline",),
        adverse_event_signals=("anemia", "fatigue", "creatinine_elevation"),
        contraindication_signals=("severe_marrow_failure", "creatinine_clearance_lt_30"),
        notes="TRITON-3 rucaparib mCRPC post-ARPI BRCA/ATM+.",
    ),
    PivotalPatientProfile(
        trial_code="IMPACT",
        nct_id="NCT00065442",
        expected_state="m1_crpc",
        expected_treatment_keywords=("sipuleucel-t", "sipuleucel"),
        payload={
            "age": 72,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "first_line",
            "pain_status": "minimal",
            "visceral_disease": 0,
        },
        comorbidity_signals=("infusion_reaction_risk",),
        adverse_event_signals=("infusion_reaction", "chills", "fatigue"),
        contraindication_signals=("visceral_metastases", "active_immunosuppression"),
        notes="IMPACT sipuleucel-T mCRPC asintomático sin viscerales.",
    ),
    PivotalPatientProfile(
        trial_code="IPATential150",
        nct_id="NCT03072238",
        expected_state="m1_crpc",
        expected_treatment_keywords=("ipatasertib", "abiraterona"),
        payload={
            "age": 68,
            "ecog_score": 0,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone",
            "mcrpc_line_context": "first_line",
            "pten_loss": 1,
        },
        comorbidity_signals=("diabetes_type2", "hypertension"),
        adverse_event_signals=("diarrea", "hyperglycemia", "rash"),
        contraindication_signals=("uncontrolled_diabetes", "child_pugh_b_or_c"),
        notes="IPATential150 PTEN-loss mCRPC 1L — ipatasertib + abiraterona.",
    ),
    PivotalPatientProfile(
        trial_code="CONTACT-02",
        nct_id="NCT04446117",
        expected_state="m1_crpc",
        expected_treatment_keywords=("cabozantinib", "atezolizumab"),
        payload={
            "age": 68,
            "ecog_score": 1,
            "known_cancer_diagnosis": 1,
            "metastatic": 1,
            "castrate_testosterone_confirmed": 1,
            "conventional_imaging_status": "M1",
            "metastasis_site": "Bone, visceral",
            "mcrpc_line_context": "post_arpi",
            "prior_arpi": 1,
            "visceral_disease": 1,
            "extra_pelvic_nodal_metastasis": 1,
            "not_chemotherapy_candidate": 1,
        },
        comorbidity_signals=("hypertension",),
        adverse_event_signals=("diarrea", "hypertension", "immune_related_aes", "fatigue"),
        contraindication_signals=("active_autoimmune_disease", "uncontrolled_hypertension"),
        notes="CONTACT-02 mCRPC post-ARPI con viscerales o nodos extra-pélvicos.",
    ),
)


def get_profile(trial_code: str) -> PivotalPatientProfile | None:
    """Devuelve el perfil insignia por código de trial."""
    for profile in PIVOTAL_PATIENT_PROFILES:
        if profile.trial_code == trial_code:
            return profile
    return None


__all__ = ["PIVOTAL_PATIENT_PROFILES", "PivotalPatientProfile", "get_profile"]
