from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class PivotalPatientProfile:
    trial_code: str
    expected_state: str
    payload: dict[str, Any]
    expected_treatment_keywords: tuple[str, ...]
    adverse_event_signals: tuple[str, ...] = field(default_factory=tuple)
    contraindication_signals: tuple[str, ...] = field(default_factory=tuple)
    notes: str = ""


_PROFILE_DATA = [{'adverse_event_signals': ('late_rt_toxicity_gi', 'late_rt_toxicity_gu'),
  'comorbidity_signals': (),
  'contraindication_signals': ('active_inflammatory_bowel_disease',),
  'expected_state': 'post_prostatectomy',
  'expected_treatment_keywords': ('radioterapia', 'salvage', 'rt'),
  'nct_id': 'NCT00541047',
  'notes': 'Patología adversa pT3a R1; salvage temprano no inferior a adyuvante.',
  'payload': {'adverse_pathology': 1,
              'age': 65,
              'early_salvage_window': 1,
              'ecog_score': 0,
              'gleason_primary': 4,
              'gleason_secondary': 3,
              'isup_grade': 3,
              'known_cancer_diagnosis': 1,
              'metastasis_site': 'M0',
              'pT_stage': 'pT3a',
              'pathological_t_stage': 'pT3a',
              'prior_prostatectomy': 1,
              'psa': 0.05,
              'psa_postop': 0.05,
              'surgical_margin_status': 'positive'},
  'trial_code': 'RADICALS-RT'},
 {'adverse_event_signals': ('hot_flashes', 'fatigue', 'hypertension', 'falls'),
  'comorbidity_signals': ('hypertension',),
  'contraindication_signals': ('severe_seizure_history',),
  'expected_state': 'recurrence_bcr',
  'expected_treatment_keywords': ('enzalutamida', 'leuprolide', 'embark'),
  'nct_id': 'NCT02319837',
  'notes': 'BCR alto-riesgo PSADT 8.5m, M0 confirmado.',
  'payload': {'age': 69,
              'bcr2': 1,
              'bcr_confirmed': 1,
              'ecog_score': 0,
              'known_cancer_diagnosis': 1,
              'metastasis_site': 'M0',
              'prior_prostatectomy': 1,
              'psa_current': 5.0,
              'psa_doubling_time_months': 8.5,
              'psa_postop': 5.0},
  'trial_code': 'EMBARK'},
 {'adverse_event_signals': ('rash', 'hypothyroidism', 'fatigue', 'hot_flashes'),
  'comorbidity_signals': ('rash_history',),
  'contraindication_signals': ('severe_hepatic_impairment',),
  'expected_state': 'recurrence_bcr',
  'expected_treatment_keywords': ('apalutamida', 'abiraterona', 'adt'),
  'nct_id': 'NCT03009981',
  'notes': 'BCR2 PSADT corto post-RP+SRT; apalutamida ± abiraterona (PRESTO).',
  'payload': {'age': 68,
              'bcr2': 1,
              'bcr_confirmed': 1,
              'conventional_imaging_m0': 1,
              'ecog_score': 0,
              'imaging_negative': 1,
              'known_cancer_diagnosis': 1,
              'metastasis_site': 'M0',
              'prior_prostatectomy': 1,
              'prior_secondary_rt': 1,
              'psa_current': 4.2,
              'psa_doubling_time_months': 7.0,
              'psa_postop': 4.2,
              'psadt_months': 7.0},
  'trial_code': 'PRESTO'},
 {'adverse_event_signals': ('neutropenia', 'neuropathy_grade2', 'fatigue'),
  'comorbidity_signals': ('neuropathy_baseline',),
  'contraindication_signals': ('severe_neuropathy_grade3', 'neutropenia_grade4_ongoing'),
  'expected_state': 'mcspc_high_volume',
  'expected_treatment_keywords': ('docetaxel', 'adt'),
  'nct_id': 'NCT00309985',
  'notes': 'mHSPC alto volumen fit; ADT + docetaxel pivote OS +13.6m.',
  'payload': {'age': 63,
              'bone_lesion_count': 6,
              'bone_lesions_outside_axial': 1,
              'docetaxel_fit': 1,
              'ecog_score': 1,
              'gleason_primary': 4,
              'gleason_secondary': 4,
              'isup_grade': 4,
              'known_cancer_diagnosis': 1,
              'metachronous_metastasis': '0',
              'metastasis_site': 'Bone, visceral',
              'metastatic': 1,
              'performance_status_driver': 'cancer_related',
              'psa': 80.0,
              'visceral_disease': 1},
  'trial_code': 'CHAARTED'},
 {'adverse_event_signals': ('hypertension', 'hypokalemia', 'hepatic_aes', 'fluid_retention'),
  'comorbidity_signals': ('hypertension', 'hypokalemia_risk'),
  'contraindication_signals': ('child_pugh_b_or_c', 'uncontrolled_hypertension', 'severe_heart_failure_nyha_iii_iv'),
  'expected_state': 'mcspc_high_volume',
  'expected_treatment_keywords': ('abiraterona', 'prednisona', 'adt'),
  'nct_id': 'NCT01715285',
  'notes': 'mHSPC LATITUDE: ≥2 factores de alto riesgo; abiraterona + ADT.',
  'payload': {'age': 67,
              'bone_lesion_count': 5,
              'docetaxel_fit': 0,
              'ecog_score': 0,
              'gleason_primary': 4,
              'gleason_secondary': 5,
              'gleason_total': 9,
              'isup_grade': 5,
              'known_cancer_diagnosis': 1,
              'metachronous_metastasis': '0',
              'metastasis_site': 'Bone, visceral',
              'metastatic': 1,
              'psa': 50.0,
              'visceral_disease': 1},
  'trial_code': 'LATITUDE'},
 {'adverse_event_signals': ('neutropenia', 'fatigue', 'hot_flashes'),
  'comorbidity_signals': (),
  'contraindication_signals': ('severe_hepatic_impairment', 'severe_heart_failure_nyha_iii_iv'),
  'expected_state': 'mcspc_high_volume',
  'expected_treatment_keywords': ('docetaxel', 'abiraterona', 'rt'),
  'nct_id': 'NCT00268476',
  'notes': 'Plataforma multi-arm; backbone STAMPEDE (G/H) trazable.',
  'payload': {'age': 65,
              'bone_lesion_count': 4,
              'bone_lesions_outside_axial': 1,
              'docetaxel_fit': 1,
              'ecog_score': 1,
              'gleason_primary': 4,
              'gleason_secondary': 4,
              'isup_grade': 4,
              'known_cancer_diagnosis': 1,
              'metachronous_metastasis': '0',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'performance_status_driver': 'cancer_related',
              'psa': 60.0},
  'trial_code': 'STAMPEDE'},
 {'adverse_event_signals': ('fatigue', 'falls', 'qtc_prolongation'),
  'comorbidity_signals': ('falls_risk',),
  'contraindication_signals': ('severe_seizure_history',),
  'expected_state': 'mcspc_high_volume',
  'expected_treatment_keywords': ('enzalutamida', 'adt'),
  'nct_id': 'NCT02446405',
  'notes': 'mHSPC alto volumen; ENZAMET admite docetaxel concurrente.',
  'payload': {'age': 68,
              'bone_lesion_count': 5,
              'docetaxel_fit': 1,
              'ecog_score': 1,
              'known_cancer_diagnosis': 1,
              'metachronous_metastasis': '0',
              'metastasis_site': 'Bone, visceral',
              'metastatic': 1,
              'performance_status_driver': 'cancer_related',
              'psa': 40.0,
              'visceral_disease': 1},
  'trial_code': 'ENZAMET'},
 {'adverse_event_signals': ('fatigue', 'hypertension', 'fractures'),
  'comorbidity_signals': ('hypertension',),
  'contraindication_signals': ('severe_seizure_history',),
  'expected_state': 'mcspc_high_volume',
  'expected_treatment_keywords': ('enzalutamida', 'adt'),
  'nct_id': 'NCT02677896',
  'notes': 'ARCHES admite docetaxel previo + ADT + enzalutamida.',
  'payload': {'age': 70,
              'bone_lesion_count': 5,
              'bone_lesions_outside_axial': 1,
              'docetaxel_fit': 0,
              'ecog_score': 1,
              'known_cancer_diagnosis': 1,
              'metachronous_metastasis': '0',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'prior_docetaxel': 1,
              'psa': 35.0},
  'trial_code': 'ARCHES'},
 {'adverse_event_signals': ('rash', 'hypothyroidism', 'fatigue', 'falls'),
  'comorbidity_signals': ('rash_history', 'hypothyroidism'),
  'contraindication_signals': ('severe_seizure_history',),
  'expected_state': 'mcspc_high_volume',
  'expected_treatment_keywords': ('apalutamida', 'adt'),
  'nct_id': 'NCT02489318',
  'notes': 'TITAN evaluó apalutamida en todo el espectro mHSPC.',
  'payload': {'age': 68,
              'bone_lesion_count': 5,
              'docetaxel_fit': 0,
              'ecog_score': 0,
              'known_cancer_diagnosis': 1,
              'metachronous_metastasis': '0',
              'metastasis_site': 'Bone, visceral',
              'metastatic': 1,
              'prior_docetaxel': 0,
              'psa': 35.0,
              'visceral_disease': 1},
  'trial_code': 'TITAN'},
 {'adverse_event_signals': ('neutropenia', 'hypertension', 'hepatic_aes', 'fluid_retention'),
  'comorbidity_signals': ('hypertension',),
  'contraindication_signals': ('child_pugh_b_or_c', 'severe_heart_failure_nyha_iii_iv', 'uncontrolled_hypertension'),
  'expected_state': 'mcspc_high_volume',
  'expected_treatment_keywords': ('triplete', 'abiraterona', 'docetaxel'),
  'nct_id': 'NCT01957436',
  'notes': 'mHSPC alto volumen sincrónico; triplete vs ADT + abiraterona.',
  'payload': {'age': 64,
              'bone_lesion_count': 6,
              'bone_lesions_outside_axial': 1,
              'docetaxel_fit': 1,
              'ecog_score': 0,
              'known_cancer_diagnosis': 1,
              'metachronous_metastasis': '0',
              'metastasis_site': 'Bone, visceral',
              'metastatic': 1,
              'performance_status_driver': 'cancer_related',
              'psa': 100.0,
              'visceral_disease': 1},
  'trial_code': 'PEACE-1'},
 {'adverse_event_signals': ('neutropenia', 'fatigue', 'rash'),
  'comorbidity_signals': (),
  'contraindication_signals': ('ecog_2_or_more',),
  'expected_state': 'mcspc_high_volume',
  'expected_treatment_keywords': ('triplete', 'darolutamida', 'docetaxel'),
  'nct_id': 'NCT02799602',
  'notes': 'ARASENS triplete; ECOG 0-1 obligatorio.',
  'payload': {'age': 63,
              'bone_lesion_count': 7,
              'bone_lesions_outside_axial': 1,
              'docetaxel_fit': 1,
              'ecog_score': 0,
              'known_cancer_diagnosis': 1,
              'metachronous_metastasis': '0',
              'metastasis_site': 'Bone, visceral',
              'metastatic': 1,
              'performance_status_driver': 'cancer_related',
              'psa': 90.0,
              'visceral_disease': 1},
  'trial_code': 'ARASENS'},
 {'adverse_event_signals': ('fatigue', 'rash', 'fractures'),
  'comorbidity_signals': ('frailty_grade1',),
  'contraindication_signals': ('severe_hepatic_impairment', 'prior_arpi_exposure_mhspc'),
  'expected_state': 'mcspc_low_volume_sync_oligo',
  'expected_treatment_keywords': ('darolutamida', 'adt'),
  'nct_id': 'NCT04736199',
  'notes': 'ARANOTE doblete sin chemo — pivote para frágil/elderly mHSPC. CI: hepatopatía severa Child-Pugh C; prior '
           'ARPI excluido del trial (Saad Lancet Oncol 2024;25:1422).',
  'payload': {'age': 72,
              'bone_lesion_count': 2,
              'docetaxel_fit': 0,
              'ecog_score': 1,
              'known_cancer_diagnosis': 1,
              'metachronous_metastasis': '0',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'psa': 18.0},
  'trial_code': 'ARANOTE'},
 {'adverse_event_signals': ('anemia', 'thrombocytopenia', 'fatigue', 'hypertension'),
  'comorbidity_signals': ('anemia_baseline',),
  'contraindication_signals': ('active_marrow_failure', 'severe_hepatic_impairment'),
  'expected_state': 'mcspc_high_volume',
  'expected_treatment_keywords': ('niraparib', 'abiraterona'),
  'nct_id': 'NCT04497844',
  'notes': 'AMPLITUDE BRCA+ enriquecido — niraparib + abiraterona en mHSPC; requiere origen BRCA2 y assay metadata '
           'para activar AKEEGA.',
  'payload': {'age': 65,
              'biomarker_source': 'ctDNA',
              'bone_lesion_count': 5,
              'brca2_origin': 'germline',
              'brca2_status': 'Positivo',
              'brca_pathway': 1,
              'ecog_score': 1,
              'germline_pathogenic_variant': 'BRCA2',
              'hrr_positive': 1,
              'known_cancer_diagnosis': 1,
              'metachronous_metastasis': '0',
              'metastasis_site': 'Bone, visceral',
              'metastatic': 1,
              'molecular_assay_date': '2025-01-10',
              'molecular_assay_source': 'ctDNA',
              'psa': 55.0,
              'visceral_disease': 1},
  'trial_code': 'AMPLITUDE'},
 {'adverse_event_signals': ('rash', 'hypothyroidism', 'falls', 'fractures'),
  'comorbidity_signals': ('falls_risk', 'rash_history'),
  'contraindication_signals': ('severe_seizure_history',),
  'expected_state': 'm0_crpc',
  'expected_treatment_keywords': ('apalutamida',),
  'nct_id': 'NCT01946204',
  'notes': 'SPARTAN nmCRPC PSADT 4.3m mediano.',
  'payload': {'age': 74,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_modality': 'CT + bone scan',
              'conventional_imaging_status': 'M0',
              'current_adt_context': 'medical_adt_continuous',
              'ecog_score': 0,
              'imaging_negative': 1,
              'known_cancer_diagnosis': 1,
              'progression_pattern': 'biochemical_only',
              'psa_doubling_time_months': 4.3,
              'psadt_months': 4.3},
  'trial_code': 'SPARTAN'},
 {'adverse_event_signals': ('fatigue', 'falls', 'qtc_prolongation'),
  'comorbidity_signals': ('falls_risk',),
  'contraindication_signals': ('severe_seizure_history',),
  'expected_state': 'm0_crpc',
  'expected_treatment_keywords': ('enzalutamida',),
  'nct_id': 'NCT02003924',
  'notes': 'PROSPER nmCRPC PSADT 3.8m mediano; falls risk relevante.',
  'payload': {'age': 74,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_modality': 'CT + bone scan',
              'conventional_imaging_status': 'M0',
              'current_adt_context': 'medical_adt_continuous',
              'ecog_score': 0,
              'imaging_negative': 1,
              'known_cancer_diagnosis': 1,
              'progression_pattern': 'biochemical_only',
              'psa_doubling_time_months': 3.8,
              'psadt_months': 3.8},
  'trial_code': 'PROSPER'},
 {'adverse_event_signals': ('fatigue', 'rash'),
  'comorbidity_signals': ('seizure_predisposition',),
  'contraindication_signals': ('severe_hepatic_impairment', 'darolutamide_hypersensitivity'),
  'expected_state': 'm0_crpc',
  'expected_treatment_keywords': ('darolutamida',),
  'nct_id': 'NCT02200614',
  'notes': 'ARAMIS nmCRPC; perfil CNS preferido (menor pase BBB) — apto para predisposición convulsiva. CI: '
           'hepatopatía severa Child-Pugh C; hipersensibilidad conocida (Fizazi NEJM 2019;380:1235).',
  'payload': {'age': 74,
              'castrate_testosterone_confirmed': 1,
              'comorbidity_seizure': 0,
              'conventional_imaging_modality': 'CT + bone scan',
              'conventional_imaging_status': 'M0',
              'current_adt_context': 'medical_adt_continuous',
              'ecog_score': 0,
              'imaging_negative': 1,
              'known_cancer_diagnosis': 1,
              'progression_pattern': 'biochemical_only',
              'psa_doubling_time_months': 4.4,
              'psadt_months': 4.4},
  'trial_code': 'ARAMIS'},
 {'adverse_event_signals': ('neutropenia', 'neuropathy', 'fatigue', 'alopecia'),
  'comorbidity_signals': ('neuropathy_baseline',),
  'contraindication_signals': ('severe_neuropathy_grade3', 'neutropenia_grade4_ongoing'),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('docetaxel', 'prednisona'),
  'nct_id': 'NCT00134056',
  'notes': 'TAX-327 fundación docetaxel mCRPC 1L.',
  'payload': {'age': 68,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'docetaxel_fit': 1,
              'ecog_score': 1,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'first_line',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'performance_status_driver': 'cancer_related',
              'prior_docetaxel': 0},
  'trial_code': 'TAX-327'},
 {'adverse_event_signals': ('neutropenia_febril', 'diarrea', 'fatiga'),
  'comorbidity_signals': ('anemia_baseline',),
  'contraindication_signals': ('hypersensitivity_polysorbate', 'severe_neutropenia_grade4'),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('cabazitaxel', 'prednisona'),
  'nct_id': 'NCT00417079',
  'notes': 'TROPIC cabazitaxel post-docetaxel.',
  'payload': {'age': 67,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'docetaxel_fit': 1,
              'ecog_score': 1,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'post_taxane',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'performance_status_driver': 'cancer_related',
              'prior_docetaxel': 1,
              'prior_taxane': 1},
  'trial_code': 'TROPIC'},
 {'adverse_event_signals': ('neutropenia_febril', 'diarrea'),
  'comorbidity_signals': ('anemia_baseline',),
  'contraindication_signals': ('severe_neutropenia_grade4',),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('cabazitaxel',),
  'nct_id': 'NCT02485691',
  'notes': 'CARD: progresión <12m a ARPI + post-docetaxel — cabazitaxel > ARPI switch.',
  'payload': {'age': 70,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'docetaxel_fit': 1,
              'ecog_score': 1,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'post_taxane',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'performance_status_driver': 'cancer_related',
              'prior_arpi': 1,
              'prior_arpi_progression_months': 8,
              'prior_docetaxel': 1},
  'trial_code': 'CARD'},
 {'adverse_event_signals': ('hypertension', 'hypokalemia', 'hepatic_aes', 'fluid_retention'),
  'comorbidity_signals': ('hypertension',),
  'contraindication_signals': ('child_pugh_b_or_c', 'uncontrolled_hypertension', 'severe_heart_failure_nyha_iii_iv'),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('abiraterona', 'prednisona'),
  'nct_id': 'NCT00638690',
  'notes': 'COU-AA-301 abiraterona post-docetaxel sintomático.',
  'payload': {'age': 69,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 1,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'post_taxane',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'pain_status': 'moderate',
              'prior_docetaxel': 1},
  'trial_code': 'COU-AA-301'},
 {'adverse_event_signals': ('hypertension', 'hypokalemia', 'hepatic_aes', 'fluid_retention'),
  'comorbidity_signals': ('hypertension',),
  'contraindication_signals': ('child_pugh_b_or_c', 'uncontrolled_hypertension', 'severe_heart_failure_nyha_iii_iv'),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('abiraterona', 'prednisona'),
  'nct_id': 'NCT00887198',
  'notes': 'COU-AA-302 abiraterona pre-chemo asintomático/leve.',
  'payload': {'age': 71,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 0,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'first_line',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'pain_status': 'minimal',
              'prior_docetaxel': 0},
  'trial_code': 'COU-AA-302'},
 {'adverse_event_signals': ('fatigue', 'falls', 'headache'),
  'comorbidity_signals': ('falls_risk',),
  'contraindication_signals': ('severe_seizure_history',),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('enzalutamida',),
  'nct_id': 'NCT00974311',
  'notes': 'AFFIRM enzalutamida post-docetaxel; excluyó historia de convulsiones.',
  'payload': {'age': 69,
              'castrate_testosterone_confirmed': 1,
              'comorbidity_seizure': 0,
              'conventional_imaging_status': 'M1',
              'ecog_score': 1,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'post_taxane',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'prior_docetaxel': 1,
              'seizure_history': 0},
  'trial_code': 'AFFIRM'},
 {'adverse_event_signals': ('fatigue', 'falls', 'headache'),
  'comorbidity_signals': ('falls_risk',),
  'contraindication_signals': ('severe_seizure_history',),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('enzalutamida',),
  'nct_id': 'NCT01212991',
  'notes': 'PREVAIL enzalutamida pre-chemo asintomático.',
  'payload': {'age': 71,
              'castrate_testosterone_confirmed': 1,
              'comorbidity_seizure': 0,
              'conventional_imaging_status': 'M1',
              'ecog_score': 0,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'first_line',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'pain_status': 'minimal',
              'prior_docetaxel': 0,
              'seizure_history': 0},
  'trial_code': 'PREVAIL'},
 {'adverse_event_signals': ('thrombocytopenia', 'anemia', 'diarrea'),
  'comorbidity_signals': ('anemia_baseline',),
  'contraindication_signals': ('visceral_metastases', 'concomitant_abiraterone_prednisone'),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('ra-223', 'radio', 'rádio'),
  'nct_id': 'NCT00699751',
  'notes': 'ALSYMPCA Ra-223 mCRPC óseo sintomático sin viscerales.',
  'payload': {'age': 72,
              'bone_lesion_count': 6,
              'bone_only_disease': 1,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 1,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'later_line',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'symptomatic_bone_only': 1,
              'visceral_disease': 0},
  'trial_code': 'ALSYMPCA'},
 {'adverse_event_signals': ('xerostomia', 'fatigue', 'anemia', 'trombocitopenia'),
  'comorbidity_signals': ('renal_dysfunction_mild',),
  'contraindication_signals': ('severe_renal_failure_egfr_lt_30', 'severe_marrow_failure'),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('lutecio', 'lu-177', 'psma', 'pluvicto'),
  'nct_id': 'NCT03511664',
  'notes': 'VISION mCRPC PSMA+ post-ARPI + post-taxano.',
  'payload': {'age': 70,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 1,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'post_taxane',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'prior_arpi': 1,
              'prior_docetaxel': 1,
              'prior_taxane': 1,
              'psma_lesion_suvmax_minimum': 18.0,
              'psma_negative_dominant_lesions': 0,
              'psma_positive': 1,
              'psma_suvmean_liver': 6.5},
  'trial_code': 'VISION'},
 {'adverse_event_signals': ('xerostomia', 'fatigue'),
  'comorbidity_signals': ('renal_dysfunction_mild',),
  'contraindication_signals': ('severe_renal_failure_egfr_lt_30',),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('lutecio', 'lu-177', 'psma', 'pluvicto'),
  'nct_id': 'NCT04689828',
  'notes': 'PSMAfore mCRPC PSMA+ pre-taxano post-ARPI.',
  'payload': {'age': 71,
              'castrate_testosterone_confirmed': 1,
              'chemotherapy_delay_candidate': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 0,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'first_line',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'prior_arpi': 1,
              'prior_docetaxel': 0,
              'prior_taxane': 0,
              'psma_lesion_suvmax_minimum': 16.0,
              'psma_negative_dominant_lesions': 0,
              'psma_positive': 1,
              'psma_suvmean_liver': 6.0},
  'trial_code': 'PSMAfore'},
 {'adverse_event_signals': ('xerostomia', 'trombocitopenia', 'diarrea'),
  'comorbidity_signals': ('anemia_baseline',),
  'contraindication_signals': ('severe_marrow_failure', 'psma_negative_dominant_lesions'),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('lutecio', 'lu-177', 'psma', 'pluvicto'),
  'nct_id': 'NCT03392428',
  'notes': 'TheraP exigió SUVmax ≥20 en al menos una lesión índice.',
  'payload': {'age': 71,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 1,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'post_taxane',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'prior_docetaxel': 1,
              'prior_taxane': 1,
              'psma_lesion_suvmax_minimum': 22.0,
              'psma_negative_dominant_lesions': 0,
              'psma_positive': 1,
              'psma_suvmean_liver': 5.5},
  'trial_code': 'TheraP'},
 {'adverse_event_signals': ('fractures', 'anemia', 'fatigue'),
  'comorbidity_signals': ('osteopenia',),
  'contraindication_signals': ('concomitant_abiraterone_prednisone', 'no_bone_protective_agent'),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('ra-223', 'radio', 'enzalutamida'),
  'nct_id': 'NCT02194842',
  'notes': 'PEACE-3 Ra-223 + enzalutamida con profilaxis ósea obligatoria.',
  'payload': {'age': 72,
              'bone_lesion_count': 5,
              'bone_modifying_agent': 'denosumab',
              'bone_only_disease': 1,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'denosumab_prophylaxis': 1,
              'ecog_score': 1,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'first_line',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'prior_arpi': 0,
              'visceral_disease': 0},
  'trial_code': 'PEACE-3'},
 {'adverse_event_signals': ('anemia', 'thromboembolism', 'nausea'),
  'comorbidity_signals': ('anemia_baseline',),
  'contraindication_signals': ('severe_marrow_failure',),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('olaparib',),
  'nct_id': 'NCT02987543',
  'notes': 'PROfound olaparib HRR+ post-ARPI.',
  'payload': {'age': 67,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 1,
              'germline_pathogenic_variant': 'BRCA2',
              'hrr_positive': 1,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'post_arpi',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'prior_arpi': 1},
  'trial_code': 'PROfound'},
 {'adverse_event_signals': ('anemia', 'hypertension', 'hypokalemia', 'fatigue'),
  'comorbidity_signals': ('hypertension',),
  'contraindication_signals': ('child_pugh_b_or_c', 'severe_heart_failure_nyha_iii_iv'),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('olaparib', 'abiraterona'),
  'nct_id': 'NCT03732820',
  'notes': 'PROpel mCRPC 1L sin ARPI previo — olaparib + abiraterona.',
  'payload': {'age': 69,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 0,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'first_line',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'prior_abiraterone': 0,
              'prior_arpi': 0},
  'trial_code': 'PROpel'},
 {'adverse_event_signals': ('anemia', 'thrombocytopenia', 'hypertension'),
  'comorbidity_signals': ('anemia_baseline',),
  'contraindication_signals': ('severe_marrow_failure',),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('niraparib', 'abiraterona'),
  'nct_id': 'NCT03748641',
  'notes': 'MAGNITUDE mCRPC 1L BRCA+ sin abiraterona previa; biomarker_source + hrr_gene requeridos para surface '
           'AKEEGA/niraparib.',
  'payload': {'age': 67,
              'biomarker_source': 'Tejido tumoral',
              'brca2_origin': 'germline',
              'brca_pathway': 1,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 1,
              'germline_pathogenic_variant': 'BRCA2',
              'hrr_gene': 'BRCA2',
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'first_line',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'molecular_report_date': '2025-02-15',
              'prior_abiraterone': 0},
  'trial_code': 'MAGNITUDE'},
 {'adverse_event_signals': ('anemia', 'neutropenia', 'fatigue'),
  'comorbidity_signals': ('anemia_baseline',),
  'contraindication_signals': ('severe_marrow_failure',),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('talazoparib', 'enzalutamida'),
  'nct_id': 'NCT03395197',
  'notes': 'TALAPRO-2 talazoparib + enzalutamida; HRR+ con beneficio primario.',
  'payload': {'age': 68,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 1,
              'germline_pathogenic_variant': 'BRCA2',
              'hrr_positive': 1,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'first_line',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'prior_arpi': 0,
              'prior_enzalutamide': 0},
  'trial_code': 'TALAPRO-2'},
 {'adverse_event_signals': ('anemia', 'fatigue', 'creatinine_elevation'),
  'comorbidity_signals': ('anemia_baseline',),
  'contraindication_signals': ('severe_marrow_failure', 'creatinine_clearance_lt_30'),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('rucaparib',),
  'nct_id': 'NCT02975934',
  'notes': 'TRITON-3 rucaparib mCRPC post-ARPI BRCA/ATM+.',
  'payload': {'age': 69,
              'brca_pathway': 1,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 1,
              'germline_pathogenic_variant': 'BRCA2',
              'hrr_positive': 1,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'post_arpi',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'prior_arpi': 1},
  'trial_code': 'TRITON-3'},
 {'adverse_event_signals': ('infusion_reaction', 'chills', 'fatigue'),
  'comorbidity_signals': ('infusion_reaction_risk',),
  'contraindication_signals': ('visceral_metastases', 'active_immunosuppression'),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('sipuleucel-t', 'sipuleucel'),
  'nct_id': 'NCT00065442',
  'notes': 'IMPACT sipuleucel-T mCRPC asintomático sin viscerales.',
  'payload': {'age': 72,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 0,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'first_line',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'pain_status': 'minimal',
              'visceral_disease': 0},
  'trial_code': 'IMPACT'},
 {'adverse_event_signals': ('diarrea', 'hyperglycemia', 'rash'),
  'comorbidity_signals': ('diabetes_type2', 'hypertension'),
  'contraindication_signals': ('uncontrolled_diabetes', 'child_pugh_b_or_c'),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('ipatasertib', 'abiraterona'),
  'nct_id': 'NCT03072238',
  'notes': 'IPATential150 PTEN-loss mCRPC 1L — ipatasertib + abiraterona.',
  'payload': {'age': 68,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 0,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'first_line',
              'metastasis_site': 'Bone',
              'metastatic': 1,
              'pten_loss': 1},
  'trial_code': 'IPATential150'},
 {'adverse_event_signals': ('diarrea', 'hypertension', 'immune_related_aes', 'fatigue'),
  'comorbidity_signals': ('hypertension',),
  'contraindication_signals': ('active_autoimmune_disease', 'uncontrolled_hypertension'),
  'expected_state': 'm1_crpc',
  'expected_treatment_keywords': ('cabozantinib', 'atezolizumab'),
  'nct_id': 'NCT04446117',
  'notes': 'CONTACT-02 mCRPC post-ARPI con viscerales o nodos extra-pélvicos.',
  'payload': {'age': 68,
              'castrate_testosterone_confirmed': 1,
              'conventional_imaging_status': 'M1',
              'ecog_score': 1,
              'extra_pelvic_nodal_metastasis': 1,
              'known_cancer_diagnosis': 1,
              'mcrpc_line_context': 'post_arpi',
              'metastasis_site': 'Bone, visceral',
              'metastatic': 1,
              'not_chemotherapy_candidate': 1,
              'prior_arpi': 1,
              'visceral_disease': 1},
  'trial_code': 'CONTACT-02'}]

PIVOTAL_PATIENT_PROFILES: tuple[PivotalPatientProfile, ...] = tuple(
    PivotalPatientProfile(
        trial_code=item["trial_code"],
        expected_state=item["expected_state"],
        payload=dict(item.get("payload") or {}),
        expected_treatment_keywords=tuple(item.get("expected_treatment_keywords") or ()),
        adverse_event_signals=tuple(item.get("adverse_event_signals") or ()),
        contraindication_signals=tuple(item.get("contraindication_signals") or ()),
        notes=str(item.get("notes") or ""),
    )
    for item in _PROFILE_DATA
)


def get_profile(trial_code: str) -> PivotalPatientProfile | None:
    wanted = str(trial_code or "").strip().upper()
    for profile in PIVOTAL_PATIENT_PROFILES:
        if profile.trial_code.upper() == wanted:
            return profile
    return None


__all__ = ["PIVOTAL_PATIENT_PROFILES", "PivotalPatientProfile", "get_profile"]
