from __future__ import annotations

from prostanet.shared.contracts import FieldSpec, module_schema


STATE_CLASSIFIER_SCHEMA = module_schema(
    "state_classifier",
    "Clasificador de estado clínico",
    "Determina el módulo adecuado antes de emitir recomendaciones terapéuticas y evita mezclar pacientes diagnósticos, localizados, recurrentes y avanzados.",
    fields=[
        FieldSpec(
            "known_cancer_diagnosis",
            "Diagnóstico confirmado de cáncer de próstata",
            "select",
            options=["1", "0"],
            default="1",
            group="Contexto diagnóstico",
            group_order=1,
            clinical_role="required",
            evidence_tags=["nccn_primary", "classifier"],
            benchmark_note="Evita enrutar a rutas terapéuticas cuando aún no existe confirmación histológica.",
        ),
        FieldSpec(
            "prior_negative_biopsy",
            "Biopsia prostática previa benigna",
            "select",
            options=["0", "1"],
            default="0",
            group="Contexto diagnóstico",
            group_order=1,
            clinical_role="required",
            evidence_tags=["negative_biopsy_followup"],
        ),
        FieldSpec(
            "prior_prostatectomy",
            "Prostatectomía radical previa por cáncer de próstata",
            "select",
            options=["0", "1"],
            default="0",
            group="Tratamiento local previo",
            group_order=2,
            clinical_role="required",
            evidence_tags=["recurrence_pathway"],
            help_text="Solo aplica si el paciente ya tuvo cáncer de próstata confirmado y recibió tratamiento local quirúrgico.",
        ),
        FieldSpec(
            "prior_radiation",
            "Radioterapia previa por cáncer de próstata",
            "select",
            options=["0", "1"],
            default="0",
            group="Tratamiento local previo",
            group_order=2,
            clinical_role="required",
            evidence_tags=["recurrence_pathway"],
            help_text="Solo aplica si el paciente ya tuvo cáncer de próstata confirmado y recibió radioterapia local para ese cáncer.",
        ),
        FieldSpec(
            "bcr_detected",
            "Recurrencia bioquímica y segunda recurrencia bioquímica sin metástasis",
            "select",
            options=["0", "1"],
            default="0",
            group="Recurrencia bioquímica",
            group_order=3,
            clinical_role="decision_refiner",
            evidence_tags=["bcr_pathway"],
            benchmark_note="En el hub rápido sirve como señal explícita para enrutar a BCR/BCR2 cuando no hay metástasis conocidas ni carril post-RT específico.",
            help_text="Active esta opción si ya existe recurrencia bioquímica documentada o una segunda recurrencia bioquímica sin metástasis a distancia.",
        ),
        FieldSpec(
            "bcr2",
            "Segunda recurrencia bioquímica tras tratamiento local",
            "select",
            options=["0", "1"],
            default="0",
            group="Recurrencia bioquímica",
            group_order=3,
            clinical_role="decision_refiner",
            evidence_tags=["bcr2_pathway"],
            benchmark_note="Solo debe activarse si ya se confirmó la elegibilidad exacta del escenario BCR2 N0M0.",
            help_text="Solo aplica si ya hubo cáncer confirmado, tratamiento local previo y una primera recurrencia bioquímica documentada.",
        ),
        FieldSpec(
            "metastatic_disease_known",
            "Enfermedad metastásica conocida",
            "select",
            options=["0", "1"],
            default="0",
            group="Carga metastásica",
            group_order=4,
            clinical_role="required",
            evidence_tags=["staging"],
            help_text="Si es No, el clasificador tratará el caso como M0 salvo que exista composición metastásica estructurada explícita por compatibilidad.",
        ),
        FieldSpec(
            "metastasis_site",
            "Sitio de metástasis",
            "select",
            help_text="Campo legacy de compatibilidad. Cuando exista composición anatómica estructurada, el backend derivará este resumen automáticamente.",
            options=["M0", "Bone", "Node", "Visceral"],
            default="M0",
            group="Carga metastásica",
            group_order=4,
            clinical_role="derived",
            evidence_tags=["staging"],
            benchmark_note="En enfermedad ósea, el volumen se deriva de la distribución anatómica axial/apendicular y no de una etiqueta manual.",
        ),
        FieldSpec(
            "metastasis_count",
            "Número de metástasis",
            "number",
            default=0,
            group="Carga metastásica",
            group_order=4,
            clinical_role="decision_refiner",
            unit="lesiones",
            evidence_tags=["staging", "chaarted"],
        ),
        FieldSpec(
            "volume_disease",
            "Volumen de enfermedad",
            "select",
            options=["Low", "High"],
            default="Low",
            group="Carga metastásica",
            group_order=4,
            clinical_role="derived",
            evidence_tags=["chaarted"],
            help_text="Campo derivado por backend para compatibilidad. En el hub rápido no se captura manualmente.",
            benchmark_note="El criterio operativo usa metástasis viscerales o >=4 lesiones óseas con al menos una apendicular.",
        ),
        FieldSpec(
            "metachronous_metastasis",
            "Metástasis metacrónicas",
            "select",
            options=["0", "1"],
            default="0",
            group="Carga metastásica",
            group_order=4,
            clinical_role="required",
            evidence_tags=["metachronous"],
            benchmark_note="Diferencia de novo frente a metacrónico para no mezclar flujos de mCSPC.",
        ),
        FieldSpec(
            "systemic_progression_context",
            "Contexto de progresión sistémica",
            "select",
            options=["none", "progression_on_adt_verify_castration", "confirmed_crpc"],
            default="none",
            group="Estado sistémico",
            group_order=5,
            clinical_role="required",
            evidence_tags=["crpc", "adt_verification"],
            benchmark_note="No etiquetar CRPC sin testosterona en rango de castración confirmada y reestadificación adecuada.",
        ),
        FieldSpec(
            "current_adt_context",
            "Contexto actual de terapia de privación androgénica (ADT)",
            "select",
            options=["none", "medical_adt_continuous", "orchiectomy", "intermittent_adt"],
            default="none",
            group="Estado sistémico",
            group_order=5,
            clinical_role="decision_refiner",
            evidence_tags=["adt_verification"],
        ),
        FieldSpec(
            "castrate_testosterone_status",
            "Estado de testosterona en rango de castración",
            "select",
            options=["confirmed_castrate", "not_castrate", "unknown"],
            default="unknown",
            group="Estado sistémico",
            group_order=5,
            clinical_role="required",
            evidence_tags=["castration_confirmation", "adt_verification"],
        ),
        FieldSpec(
            "progression_pattern",
            "Patrón de progresión",
            "select",
            options=["biochemical_only", "radiographic", "clinical", "mixed"],
            default="biochemical_only",
            group="Estado sistémico",
            group_order=5,
            clinical_role="decision_refiner",
            evidence_tags=["progression_pattern"],
        ),
        FieldSpec(
            "conventional_imaging_status",
            "Estado de imagen convencional",
            "select",
            options=["not_restaged", "M0", "M1"],
            default="not_restaged",
            group="Estado sistémico",
            group_order=5,
            clinical_role="decision_refiner",
            evidence_tags=["staging", "crpc"],
        ),
    ],
)
