from __future__ import annotations

from prostanet.shared.contracts import FieldSpec, module_schema
from prostanet.shared.advanced_support_fields import (
    advanced_adt_timeline_fields,
    advanced_chemotherapy_fitness_fields,
    advanced_cognitive_fields,
    advanced_ddi_fields,
    advanced_hepatic_fields,
    advanced_laboratory_baseline_fields,
    advanced_neutropenia_fields,
    advanced_pro_dropdown_fields,
    advanced_renal_function_fields,
    advanced_variant_histology_fields,
    advanced_visceral_site_fields,
    oncologic_emergency_fields,
    pivotal_contraindication_fields,
    pivotal_gate_supporting_fields,
)


MCSPC_LOW_VOLUME_SCHEMA = module_schema(
    "mcspc_low_volume_sync_oligo",
    "mCSPC bajo volumen o oligometastásico sincrónico",
    "Ruta de dobletes, tripletes seleccionados y radioterapia al primario para enfermedad metastásica sensible a la castración de bajo volumen.",
    fields=[
        FieldSpec(
            "metastatic_components_capture",
            "Distribución metastásica documentada",
            "metastatic_components",
            required=True,
            group="Carga metastásica",
            group_order=1,
            clinical_role="required",
            help_text="Capture hueso, víscera y ganglios no regionales como componentes coexistentes cuando corresponda. El volumen se deriva por backend desde esta distribución.",
            benchmark_note="Evita pedir un sitio metastásico único cuando el caso es mixto o cuando la clasificación depende de la anatomía detallada.",
        ),
        FieldSpec(
            "gleason_score",
            "Perfil Gleason / ISUP",
            "gleason_profile",
            default={"gleason_primary": "3", "gleason_secondary": "4", "gleason_tertiary": "", "gleason_score": "7", "isup_grade": "2"},
            group="Carga metastásica",
            group_order=1,
            clinical_role="decision_refiner",
            help_text="Documente patrón primario, secundario y el terciario si existe. El sistema derivará automáticamente el Gleason total y el ISUP para sostener la estratificación clínica.",
        ),
        FieldSpec("rt_primary_received", "Radioterapia local previa", "select", options=["0", "1"], default="0", group="Tratamiento local", group_order=2, clinical_role="required"),
        FieldSpec(
            "bone_lesions_outside_axial",
            "Lesiones óseas fuera del esqueleto axial",
            "select",
            options=["", "0", "1"],
            default="",
            group="Carga metastásica",
            group_order=1,
            clinical_role="decision_refiner",
            evidence_tags=["chaarted", "high_volume"],
            help_text="Apendicular (huesos largos / costillas / cráneo) — con ≥4 mets óseos cumple alto volumen CHAARTED.",
        ),
        FieldSpec(
            "extra_pelvic_nodal_metastasis",
            "Adenopatías metastásicas extra-pélvicas",
            "select",
            options=["", "0", "1"],
            default="",
            group="Carga metastásica",
            group_order=1,
            clinical_role="decision_refiner",
            evidence_tags=["contact02", "extra_pelvic"],
        ),
        FieldSpec(
            "bone_lesion_count",
            "Número total de lesiones óseas",
            "number",
            default="",
            group="Carga metastásica",
            group_order=1,
            clinical_role="decision_refiner",
            unit="lesiones",
            evidence_tags=["chaarted", "latitude"],
        ),
        FieldSpec(
            "metachronous_metastasis",
            "Metástasis metacrónicas (>12m post-tratamiento local)",
            "select",
            options=["Desconocido", "No", "Sí"],
            default="Desconocido",
            group="Carga metastásica",
            group_order=1,
            clinical_role="decision_refiner",
            evidence_tags=["latitude", "metachronous"],
            help_text=(
                "Metástasis metacrónica (aparecida >6-12m tras enfermedad localizada). "
                "Relevante para LATITUDE oligo. Acepta legacy boolean '0'/'1'."
            ),
        ),
        FieldSpec(
            "pten_loss",
            "Pérdida de PTEN (IHC o NGS)",
            "select",
            options=["", "0", "1", "Desconocido"],
            default="",
            group="Biomarcadores",
            group_order=4,
            clinical_role="decision_refiner",
            evidence_tags=["capitello281", "ipatential150"],
            help_text="Gatilla CAPItello-281 (capivasertib + abiraterona) en mHSPC.",
        ),
        *advanced_visceral_site_fields(group="Sitios viscerales estructurados", group_order=2),
        *advanced_adt_timeline_fields(group="Terapia de privación androgénica", group_order=2),
        FieldSpec("ecog_score", "ECOG", "number", default=0, group="Fitness y seguridad", group_order=3, clinical_role="required", unit="0-4"),
        FieldSpec("frailty_status", "Fragilidad clínica", "select", options=["Fit", "Vulnerable", "Frail"], default="Fit", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["frailty"]),
        *advanced_hepatic_fields(group="Fitness y seguridad", group_order=3, child_pugh_role="required"),
        *advanced_renal_function_fields(group="Función renal basal", group_order=3),
        *advanced_laboratory_baseline_fields(group="Marcadores pronósticos Halabi", group_order=3),
        FieldSpec("comorbidity_seizure", "Riesgo convulsivo", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner"),
        FieldSpec("comorbidity_cardio", "Riesgo cardiovascular", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["cardio_oncology"]),
        FieldSpec("cv_risk_documented", "Riesgo cardiovascular documentado", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="monitoring", evidence_tags=["cardio_oncology"]),
        *advanced_ddi_fields(group="Fitness y seguridad", group_order=3),
        FieldSpec("dermatitis_history", "Antecedente dermatológico relevante", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["arsi_safety"]),
        FieldSpec("cognitive_risk", "Riesgo cognitivo clínicamente relevante", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["neurotoxicity"]),
        FieldSpec("fall_risk", "Riesgo de caídas", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["falls"]),
        FieldSpec("stroke_history", "Antecedente de EVC/AIT", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["neurovascular"]),
        FieldSpec("edema_risk", "Riesgo de edema / IC", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["cardio_oncology"]),
        FieldSpec("steroid_intolerance", "Intolerancia a esteroides", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["steroids"]),
        FieldSpec("diabetes_uncontrolled", "Diabetes no controlada", "select", options=["0", "1"], default="0", group="Fitness y seguridad", group_order=3, clinical_role="decision_refiner", evidence_tags=["metabolic_risk"]),
        FieldSpec("baseline_bp", "Presión arterial basal sistólica", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="mmHg", evidence_tags=["cardio_oncology"]),
        FieldSpec("baseline_weight", "Peso basal", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="kg", evidence_tags=["qol"]),
        *advanced_cognitive_fields(group="Monitoreo basal ARPI", group_order=4),
        FieldSpec("fall_history_recent", "Caídas recientes", "select", options=["0", "1"], default="0", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", evidence_tags=["falls"]),
        FieldSpec("liver_panel_date", "Fecha de pruebas hepáticas basales", "date", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", evidence_tags=["hepatotoxicity"]),
        FieldSpec("bilirubin", "Bilirrubina total", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="mg/dL", evidence_tags=["hepatotoxicity"]),
        FieldSpec("ast", "AST (TGO)", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="U/L", evidence_tags=["hepatotoxicity"]),
        FieldSpec("alt", "ALT (TGP)", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="U/L", evidence_tags=["hepatotoxicity"]),
        FieldSpec("alp", "Fosfatasa alcalina", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="U/L", evidence_tags=["hepatotoxicity"]),
        FieldSpec("potassium", "Potasio basal", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", unit="mEq/L", evidence_tags=["metabolic_risk"]),
        FieldSpec("glucose_or_hba1c", "Glucosa o HbA1c basal", "number", default="", group="Monitoreo basal ARPI", group_order=4, clinical_role="monitoring", evidence_tags=["metabolic_risk"]),
        FieldSpec("molecular_assay_source", "Fuente del ensayo molecular", "select", options=["Desconocida", "Tejido primario", "Biopsia metastásica", "ctDNA"], default="Desconocida", group="Biomarcadores", group_order=4, clinical_role="decision_refiner", evidence_tags=["biomarkers"]),
        FieldSpec("molecular_assay_date", "Fecha del ensayo molecular", "date", group="Biomarcadores", group_order=4, clinical_role="decision_refiner", evidence_tags=["biomarkers"]),
        FieldSpec("hrr_gene", "Gen HRR predominante", "select", options=["Desconocido", "BRCA2", "BRCA1", "ATM", "PALB2", "CDK12", "Otro"], default="Desconocido", group="Biomarcadores", group_order=4, clinical_role="optional", evidence_tags=["hrr"], conditional_visibility={'hrr_status': ['Positivo']}),
        FieldSpec("brca2_status", "Estado BRCA2", "select", options=["Desconocido", "Positivo", "Negativo"], default="Desconocido", group="Biomarcadores", group_order=4, clinical_role="decision_refiner", evidence_tags=["hrr"]),
        FieldSpec("dxa_baseline_done", "DXA basal realizada", "select", options=["0", "1"], default="0", group="Salud ósea", group_order=5, clinical_role="monitoring", evidence_tags=["bone_health"]),
        FieldSpec("calcium_vitd_started", "Calcio y vitamina D iniciados", "select", options=["0", "1"], default="0", group="Salud ósea", group_order=5, clinical_role="monitoring", evidence_tags=["bone_health"]),
        FieldSpec("bone_protection_started", "Protección ósea iniciada", "select", options=["0", "1"], default="0", group="Salud ósea", group_order=5, clinical_role="monitoring", evidence_tags=["bone_health"]),
        *advanced_variant_histology_fields(group="Salud ósea", group_order=5, include_neuroendocrine_toggle=True),
        *advanced_pro_dropdown_fields(group="Resultados reportados por el paciente", group_order=4),
        *advanced_chemotherapy_fitness_fields(group="Aptitud a quimioterapia", group_order=52),
        *advanced_neutropenia_fields(group="Seguridad hematológica", group_order=55),
        # ── Triaje de emergencias oncológicas (Brecha 2026-04-23) ──────
        # NCCN Oncologic Emergencies v3.2026 + Loblaw 2012 + EAU §6.5.5.
        # mCSPC bajo volumen sincrónico puede debutar con compresión
        # incipiente o hipercalcemia paraneoplásica aún con baja carga.
        *oncologic_emergency_fields(role="decision_refiner", group_order=70),
        # ── Contraindicaciones de ensayos pivote (FAUBOT 2026-04-23) ──
        # ARANOTE / LATITUDE / PEACE-1 / IPATential150 / ERA-223 / PEACE-3.
        # Habilita los 10 gates de pivotal_contraindication_gates.py.
        *pivotal_contraindication_fields(role="decision_refiner", group_order=80),
        # ── Soportes pivotal gates 56-70 (Faubot LXXV/LXXVI/LXXVII #67A/B/C) ──
        *pivotal_gate_supporting_fields(role="decision_refiner", group_order=81),
    ],
)
