from __future__ import annotations

from prostanet.shared.contracts import FieldSpec, module_schema


ADT_PROGRESSION_VERIFICATION_SCHEMA = module_schema(
    "adt_progression_verification",
    "Progresión bajo ADT / verificación de castración",
    "Ruta puente para verificar castración adecuada, patrón de progresión e imagen convencional antes de etiquetar enfermedad resistente a la castración sin metástasis o con metástasis.",
    fields=[
        FieldSpec(
            "current_adt_context",
            "Contexto actual de terapia de privación androgénica (ADT)",
            "select",
            required=True,
            options=["medical_adt_continuous", "orchiectomy", "intermittent_adt", "none"],
            default="medical_adt_continuous",
            group="Supresión androgénica",
            group_order=1,
            clinical_role="required",
            evidence_tags=["adt_verification"],
        ),
        FieldSpec(
            "last_adt_date",
            "Fecha de la última administración de ADT",
            "date",
            group="Supresión androgénica",
            group_order=1,
            clinical_role="monitoring",
            evidence_tags=["adt_verification"],
        ),
        FieldSpec(
            "orchiectomy_status",
            "Orquiectomía realizada",
            "select",
            options=["0", "1"],
            default="0",
            group="Supresión androgénica",
            group_order=1,
            clinical_role="decision_refiner",
            evidence_tags=["adt_verification"],
        ),
        FieldSpec(
            "testosterone_value",
            "Testosterona actual",
            "number",
            default=0,
            group="Verificación biológica",
            group_order=2,
            clinical_role="required",
            unit="ng/dL",
            evidence_tags=["castration_confirmation"],
        ),
        FieldSpec(
            "castrate_testosterone_status",
            "Estado de testosterona en rango de castración",
            "select",
            required=True,
            options=["confirmed_castrate", "not_castrate", "unknown"],
            default="unknown",
            group="Verificación biológica",
            group_order=2,
            clinical_role="required",
            evidence_tags=["castration_confirmation"],
        ),
        FieldSpec(
            "progression_pattern",
            "Patrón de progresión",
            "select",
            options=["biochemical_only", "radiographic", "clinical", "mixed"],
            default="biochemical_only",
            group="Progresión",
            group_order=3,
            clinical_role="required",
            evidence_tags=["progression_pattern"],
        ),
        FieldSpec(
            "psa_current",
            "Antígeno prostático específico actual (PSA)",
            "number",
            default=0.2,
            group="Progresión",
            group_order=3,
            clinical_role="decision_refiner",
            unit="ng/mL",
            evidence_tags=["psa_kinetics"],
        ),
        FieldSpec(
            "psadt_months",
            "Tiempo de duplicación del PSA",
            "number",
            default=9,
            group="Progresión",
            group_order=3,
            clinical_role="decision_refiner",
            unit="meses",
            evidence_tags=["psa_kinetics"],
        ),
        FieldSpec(
            "conventional_imaging_status",
            "Estado de imagen convencional",
            "select",
            required=True,
            options=["not_restaged", "M0", "M1"],
            default="not_restaged",
            group="Reestadificación",
            group_order=4,
            clinical_role="required",
            evidence_tags=["staging", "crpc"],
        ),
        FieldSpec(
            "symptoms_progression",
            "Síntomas de progresión clínica",
            "select",
            options=["0", "1"],
            default="0",
            group="Reestadificación",
            group_order=4,
            clinical_role="decision_refiner",
            evidence_tags=["progression_pattern"],
        ),
        FieldSpec(
            "prior_local_therapy_context",
            "Tratamiento local previo relevante",
            "select",
            options=["none", "prostatectomy", "radiotherapy", "both"],
            default="none",
            group="Contexto clínico",
            group_order=5,
            clinical_role="decision_refiner",
            evidence_tags=["recurrence_pathway", "adt_verification"],
        ),
    ],
)

