"""
Agent input/output contracts.

Standardized dataclasses for agent communication, ensuring uniform
interface between agents, event bus, and the recalculation engine.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from prostanet.shared.utc_time import utc_now_iso  # EPIC 32.G G78


@dataclass
class AgentInput:
    """Input payload for any clinical agent."""

    patient_id: int
    record: dict[str, Any]         # Full patient record (from get_patient_full_record)
    trigger_event: str             # Event type that triggered this agent
    trigger_data: dict[str, Any] = field(default_factory=dict)
    timestamp: str = ""
    request_id: str = ""           # Unique ID for audit trail

    def __post_init__(self) -> None:
        if not self.timestamp:
            # EPIC 32.G (GodiBot G78 MOD) — utc_now_iso() reemplaza
            # datetime.utcnow().isoformat() (deprecated 3.12+, naive UTC).
            self.timestamp = utc_now_iso()


@dataclass
class AgentRecommendation:
    """A single structured clinical recommendation."""

    action: str                     # What to do (e.g., "Iniciar Enzalutamida 160mg/día")
    category: str                   # Treatment, restaging, monitoring, referral, etc.
    priority: str = "standard"      # critical, high, standard, low
    evidence_basis: list[str] = field(default_factory=list)  # Guideline/trial citations
    alternatives: list[str] = field(default_factory=list)
    data_requirements: list[str] = field(default_factory=list)  # What data would help
    predicted_outcome: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "action": self.action,
            "category": self.category,
            "priority": self.priority,
            "evidence_basis": self.evidence_basis,
            "alternatives": self.alternatives,
            "data_requirements": self.data_requirements,
            "predicted_outcome": self.predicted_outcome,
        }


@dataclass
class AgentAlert:
    """Clinical alert generated by an agent."""

    alert_type: str                # psa_kinetics, laboratory, ai_anomaly, etc.
    severity: str                  # critical, warning, info
    title: str
    message: str
    category: str = ""             # decision_blocker, safety, protocol_due, etc.
    recommended_action: str = ""
    evidence_basis: list[str] = field(default_factory=list)
    probability: float | None = None  # For AI-generated probability alerts

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            "alert_type": self.alert_type,
            "severity": self.severity,
            "title": self.title,
            "message": self.message,
            "category": self.category,
            "recommended_action": self.recommended_action,
            "evidence_basis": self.evidence_basis,
        }
        if self.probability is not None:
            d["probability"] = self.probability
        return d


@dataclass
class AgentOutput:
    """Standardized output from any clinical agent."""

    agent_id: str
    patient_id: int
    recommendations: list[AgentRecommendation] = field(default_factory=list)
    confidence_score: float = 0.0   # 0-100
    evidence_chain: list[str] = field(default_factory=list)  # Reasoning steps
    data_gaps: list[str] = field(default_factory=list)       # Missing inputs
    alerts: list[AgentAlert] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    execution_time_ms: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "agent_id": self.agent_id,
            "patient_id": self.patient_id,
            "recommendations": [r.to_dict() for r in self.recommendations],
            "confidence_score": self.confidence_score,
            "evidence_chain": self.evidence_chain,
            "data_gaps": self.data_gaps,
            "alerts": [a.to_dict() for a in self.alerts],
            "execution_time_ms": self.execution_time_ms,
        }


@dataclass
class QAValidation:
    """Quality assurance validation result."""

    approved: bool = True
    flags: list[str] = field(default_factory=list)
    missing_data_alerts: list[str] = field(default_factory=list)
    guideline_concordance: dict[str, bool] = field(default_factory=dict)
    escalation_needed: bool = False
    escalation_reason: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "approved": self.approved,
            "flags": self.flags,
            "missing_data_alerts": self.missing_data_alerts,
            "guideline_concordance": self.guideline_concordance,
            "escalation_needed": self.escalation_needed,
            "escalation_reason": self.escalation_reason,
        }
